### ISSUE TITLE
How to support mtu in rtc::Configuration

### ISSUE THREAD

**Issue by DZLiao** [murat-dogan/node-datachannel#109]
Good day.
Refer to libdatachannel project, more issues let me know the mtu config value is important for different networks. Is it possible to support mut config value for node-libdatachannel.

[https://github.com/paullouisageneau/libdatachannel/issues/345](https://github.com/paullouisageneau/libdatachannel/issues/345)
[https://github.com/paullouisageneau/libdatachannel/pull/349](https://github.com/paullouisageneau/libdatachannel/pull/349)

Thanks

**Comment by murat-dogan** [comment]
Hi,
Resolved with https://github.com/murat-dogan/node-datachannel/pull/110.

Will be released with nex version.

**Comment by DZLiao** [comment]
> Hi, Resolved with #110.
> 
> Will be released with next version.

It's great, thanks for the help.
