### ISSUE TITLE
32bit windows builds

### ISSUE THREAD

**Issue by porsager** [murat-dogan/node-datachannel#11]
Hi.

So nice to find this wrapper for libdatachannel. It's a great alternative for `wrtc` ! Good job!

Is there any chance that you could provide prebuilt versions for windows 32 bit as well? I've been trying to compile it myself, but so far without any luck, probably because I'm trying to build 32 bit on a 64 bit machine.

I'd be willing to sponsor this addition!

**Comment by murat-dogan** [comment]
Hi,

I am using github CI for build process. As I see github actions does not have 32-bit OS's.
Maybe I can use docker image for 32 bit.

Let me check.

**Comment by porsager** [comment]
I compile a lot of node libraries for 32bit on a 64bit windows, so I imagine it should be possible with the right configuration.
I got some of the way by installing OpenSSL 32bit and adding these cmake configs to `package.json`
```
"cmake-js": {
    "runtime": "node",
    "runtimeVersion": "12.14.1",
    "arch": "ia32"
  }
```

It built without errors, but the resulting binary unfortunately doesn't work when  requiring in node (throws `Error: The specified module could not be found.`). I've seen that error before if there was a missing dependency, usual vcruntime.dll or something like that, but I'm still digging.

**Comment by murat-dogan** [comment]
Hi,

Could you please try these binaries ?
https://github.com/murat-dogan/node-datachannel/releases/tag/v0.0.13

You should be running 32-bit nodejs binaries.

**Comment by porsager** [comment]
Ok, just tried it. It also throws with `Error: The specified module could not be found.`.

Looking at it in dependency walker it seems like it can't find `libcrypto-1_1.dll` and `libssl-1_1.dll`.

**Comment by murat-dogan** [comment]
Could you please confirm that you have `build/Release/node-datachannel.node` file under `node-datachannel` folder?

**Comment by porsager** [comment]
Yes, it's there. Just confirmed. There's a difference between the error if the file is not there and if there's a dependency missing or something wring inside the binary. If it's not there at all I get `MODULE_NOT_FOUND` error.

**Comment by murat-dogan** [comment]
Ok I guess I found the problem. It is linking openssl as dynamic library, so looking for openssl dlls.
Copying openssl dlls to `build/Release` folder will do the trick.
You can download from here -> https://slproweb.com/products/Win32OpenSSL.html

I will look to find a way to build it statically.

**Comment by porsager** [comment]
Yep :) Just tried the same as well, which worked.

It might be the same issue for the 64 bit build since I just realized I tested that one on my dev machine which has the dll's in system32. 

Would be really nice if you could make it build statically.

**Comment by porsager** [comment]
Latest release works great @murat-dogan - Thank you very much!

How can I compensate you for your time? (you can reach me on rasmus @ my username .com )

**Comment by murat-dogan** [comment]
Statically built libraries( including x86) is ready.
Please check & confirm it is working from your side.
https://github.com/murat-dogan/node-datachannel/releases/tag/v0.0.14

**Comment by murat-dogan** [comment]
> Latest release works great @murat-dogan - Thank you very much!
> 
> How can I compensate you for your time? (you can reach me on rasmus @ my username .com )

Nothing needed. Thank you for asking.

**Comment by murat-dogan** [comment]
Hello @porsager ,

I want to ask if you still need/use Win x86 binaries.
I want to be sure that there is still someone that uses it :)

Thanks,
