### ISSUE TITLE
Sorry, I don't think this is an example for beginners

### ISSUE THREAD

**Issue by Canees** [murat-dogan/node-datachannel#112]
https://github.com/murat-dogan/node-datachannel/blob/fb4a78d9f633585c07dc03af967fcfb426a4de69/examples/media/media.js#L50

It just shakes hands with main.html and sends the stream to main.js,

The stream that main.js transmits through UDPsocket is not shown in main.html,

If so, is main.html also a UDP stream?

Do I understand this correctly?

**Comment by Canees** [comment]
![image](https://user-images.githubusercontent.com/40012261/170675925-7feec21b-f291-45c1-b7ba-c8eb4c9f5394.png)

Very good. It's working. Maybe it's not very good for video transmission

**Comment by paullouisageneau** [comment]
To clarify, the example shows how WebRTC can be leveraged to capture video in the browser (main.html) and stream it to an external application (main.js). The external application receives the video stream and forwards it on local UDP port 5000, so it can be processed in another application.

**Comment by Canees** [comment]
> To clarify, the example shows how WebRTC can be leveraged to capture video in the browser (main.html) and stream it to an external application (main.js). The external application receives the video stream and forwards it on local UDP port 5000, so it can be processed in another application.

Thank you for your answer
