### ISSUE TITLE
Pre-built binary for Linux arm64?

### ISSUE THREAD

**Issue by kare** [murat-dogan/node-datachannel#116]
Is it possible to have a pre-built binary for Linux arm64 platform?

**Comment by murat-dogan** [comment]
Hi,
We already have arm64 binaries actually.
Please check here for node v17 
https://github.com/murat-dogan/node-datachannel/releases/download/v0.3.4/node-datachannel-v0.3.4-node-v102-linux-arm64.tar.gz

Is this what you are asking?

**Comment by kare** [comment]
Related to #115 I was wondering if it would be possible to skip compilation process during `npm install` and workaround the issue #115. I wasn't aware that pre-built binaries already exist.

**Comment by murat-dogan** [comment]
Yes it should download the pre-built library by default.
`prebuild-install || (npm install --ignore-scripts && npm run _prebuild)`

`prebuild-install` command will do the job.

Which node version are you using?

**Comment by kare** [comment]
Environment is the same as #115: AWS Elastic Beanstalk, AWS Linux 2 and Node v16.13.1

**Comment by murat-dogan** [comment]
I am sorry but I didn't use AWS Elastic Beanstalk before.
It should install prebuild libs anyway.

Could you please call `npm install` with `--loglevel verbose` and share it

**Comment by kare** [comment]
AWS EB runs the `npm install` command as root (for some unknown reason). I'm including two versions:
- [`npm --production install --loglevel verbose`](https://github.com/murat-dogan/node-datachannel/files/8949237/npm_install.txt)
- [`sudo npm --production install --loglevel verbose`](https://github.com/murat-dogan/node-datachannel/files/8949246/sudo_npm_install.txt)

Looks like this issue can be closed.

**Comment by murat-dogan** [comment]
Thanks for the logs.
Using `sudo` is problematic.
If you have to use it then I guess you should add `--unsafe-perm=true` as arg.

**Comment by kare** [comment]
I don't have control over using `sudo`. When I update an application in AWS Elastic Beanstalk. AWS EB executes `npm --production install` as part of the process. AWS EB executes that command with `webapp` user account. However, somewhere in the process something writes `/root/.npm/_logs` with `root` permissions.

**Comment by murat-dogan** [comment]
That's weird. 
I checked `prebuild` and `prebuild-install` commands. I could not find anything that could use `sudo`.
Is there any other package that could cause that?

**Comment by kare** [comment]
I'll try to work around this issue by installing the app directly on EC2 server without Elastic Beanstalk. Let's see if works out. It's possible that it's some other dependency, but node-datachannel was reported by npm.

**Comment by murat-dogan** [comment]
For arm64, OpenSSL required locally. We are linking it dynamically.
Please check here; 
https://github.com/murat-dogan/node-datachannel/blob/95ec9b8a6f48415571d6f69d10a351f9002a8854/CMakeLists.txt#L20

 
I tried to link it statically again and got same error;
```
[100%] Linking CXX shared library Release/node_datachannel.node
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: ../sysroot/usr/lib/aarch64-linux-gnu/libcrypto.a(sha1-armv8.o): relocation R_AARCH64_PREL64 against symbol `OPENSSL_armcap_P' which may bind externally can not be used when making a shared object; recompile with -fPIC
../sysroot/usr/lib/aarch64-linux-gnu/libcrypto.a(sha1-armv8.o): in function `sha1_block_armv8':
(.text+0x1240): dangerous relocation: unsupported relocation
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: ../sysroot/usr/lib/aarch64-linux-gnu/libcrypto.a(chacha-armv8.o): relocation R_AARCH64_PREL64 against symbol `OPENSSL_armcap_P' which may bind externally can not be used when making a shared object; recompile with -fPIC
../sysroot/usr/lib/aarch64-linux-gnu/libcrypto.a(chacha-armv8.o):(.text+0x20): dangerous relocation: unsupported relocation
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: ../sysroot/usr/lib/aarch64-linux-gnu/libcrypto.a(poly1305-armv8.o): relocation R_AARCH64_ADR_PREL_LO21 against symbol `poly1305_blocks' which may bind externally can not be used when making a shared object; recompile with -fPIC
../sysroot/usr/lib/aarch64-linux-gnu/libcrypto.a(poly1305-armv8.o): in function `poly1305_init':
(.text+0x40): dangerous relocation: unsupported relocation
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: ../sysroot/usr/lib/aarch64-linux-gnu/libcrypto.a(poly1305-armv8.o): relocation R_AARCH64_ADR_PREL_LO21 against symbol `poly1305_emit' which may bind externally can not be used when making a shared object; recompile with -fPIC
(.text+0x48): dangerous relocation: unsupported relocation
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: ../sysroot/usr/lib/aarch64-linux-gnu/libcrypto.a(poly1305-armv8.o): relocation R_AARCH64_PREL64 against symbol `OPENSSL_armcap_P' which may bind externally can not be used when making a shared object; recompile with -fPIC
../sysroot/usr/lib/aarch64-linux-gnu/libcrypto.a(poly1305-armv8.o): in function `poly1305_emit_neon':
(.text+0x9a0): dangerous relocation: unsupported relocation
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: ../sysroot/usr/lib/aarch64-linux-gnu/libcrypto.a(sha256-armv8.o): relocation R_AARCH64_PREL64 against symbol `OPENSSL_armcap_P' which may bind externally can not be used when making a shared object; recompile with -fPIC
../sysroot/usr/lib/aarch64-linux-gnu/libcrypto.a(sha256-armv8.o): in function `sha256_block_data_order':
(.text+0xf88): dangerous relocation: unsupported relocation
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: ../sysroot/usr/lib/aarch64-linux-gnu/libcrypto.a(sha512-armv8.o): relocation R_AARCH64_PREL64 against symbol `OPENSSL_armcap_P' which may bind externally can not be used when making a shared object; recompile with -fPIC
../sysroot/usr/lib/aarch64-linux-gnu/libcrypto.a(sha512-armv8.o): in function `sha512_block_data_order':
(.text+0x10c8): dangerous relocation: unsupported relocation
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/node_datachannel.dir/build.make:247: Release/node_datachannel.node] Error 1
make[1]: *** [CMakeFiles/Makefile2:316: CMakeFiles/node_datachannel.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
ERR! OMG Process terminated: 2
```
