### ISSUE TITLE
Add support for enableIceUdpMux options

### ISSUE THREAD

**Issue by k8w** [murat-dogan/node-datachannel#121]
> Allowing to multiplex all Peer Connections on the same UDP port would indeed be pretty useful on server side.

See https://github.com/paullouisageneau/libdatachannel/pull/570

**Comment by k8w** [comment]
`enableIceUdpMux`

I see it here: https://github.com/murat-dogan/node-datachannel/blob/master/src/peer-connection-wrapper.cpp

But miss it here: https://github.com/murat-dogan/node-datachannel/blob/master/lib/index.d.ts

**Comment by murat-dogan** [comment]
Thank you for reporting this.
Fixed with 66c58e4dc59599ed80656764f419374d7e790b16 and will be released with v0.3.5
