### ISSUE TITLE
Add an example sending an encoded stream with datachannel

### ISSUE THREAD

**Issue by Canees** [murat-dogan/node-datachannel#122]
Can you create a media sender example to send data packets with libx264 encoders such as ffmpeg

If I succeed in doing this in my own project, I will try to put forward such an example.

**Comment by Canees** [comment]
I tried it, but localDescription was null, please help me .
![image](https://user-images.githubusercontent.com/40012261/178955052-d61c988c-226a-4a96-b2da-50e54284dd23.png)

**Comment by paullouisageneau** [comment]
This is expected as the local description is only present *after* `setLocalDescription()` is called, provided a track has been added with `addTrack()` beforehand.

Note than rather than getting the offer synchronously with `localDescription()`, you should use the `onLocalDescription` callback to get it and send it.

**Comment by murat-dogan** [comment]
Hi,
Sorry for late reply. As @paullouisageneau commented it is expected and ok.
If you have a working example for this then please create a PR.
It will be great.
Thanks,

**Comment by Canees** [comment]
> Hi, Sorry for late reply. As @paullouisageneau commented it is expected and ok. If you have a working example for this then please create a PR. It will be great. Thanks,

of course

**Comment by Canees** [comment]
> This is expected as the local description is only present _after_ `setLocalDescription()` is called, provided a track has been added with `addTrack()` beforehand.
> 
> Note than rather than getting the offer synchronously with `localDescription()`, you should use the `onLocalDescription` callback to get it and send it.
I may not have made myself clear. 
Peer1 use datachannel create offer send to peer2(Web),I used the demo of datachannel in WEbRTC:
https://github.com/mdn/samples-server/tree/master/s/webrtc-simple-datachannel

Whether it can't send an offer unsolicited:
![image](https://user-images.githubusercontent.com/40012261/179647976-020f2d8c-23e5-4beb-af75-7d8ad7ce13a5.png)

**Comment by paullouisageneau** [comment]
The API is quite simplified and there is no `createOffer()` method like in the browser WebRTC API. With the browser API it's actually good practice to just call `setLocalDescription()` [without a manual description](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/setLocalDescription#implicit_description) so the signaling state is handled for you.

Here, just call `setLocalDescription()` to create and set the offer. You might pass an explicit argument to force an offer but it's not useful.

The code should look like this:
```js
init() {
    this.Peer.onLocalDescription((sdp, type) => {
       this.socket.emit('msg',  { sdp, type });
    });
    this.Peer.onLocalCandidate(candidate, mid) => {
       this.socket.emit('msg', { candidate, mid });
    });
}

msg(data) {
    if (data.type == 'offer' || data.type == 'answer') {
        this.Peer.setRemoteDescription(data.sdp, data.type);
    } else if (data.type == 'candidate') {
        this.Peer.setRemoteCandidate(data.candidate, data.mid);
    } else if (data.type == 'startRTC') {
        this.Peer.setLocalDescription();
    }
}
```

**Comment by Canees** [comment]
> The API is quite simplified and there is no `createOffer()` method like in the browser WebRTC API. With the browser API it's actually good practice to just call `setLocalDescription()` [without a manual description](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/setLocalDescription#implicit_description) so the signaling state is handled for you.
> 
> Here, just call `setLocalDescription()` to create and set the offer. You might pass an explicit argument to force an offer but it's not useful.
> 
> The code should look like this:
> 
> ```js
> init() {
>     this.Peer.onLocalDescription((sdp, type) => {
>        this.socket.emit('msg',  { sdp, type });
>     });
>     this.Peer.onLocalCandidate((candidate, mid) => {
>        this.socket.emit('msg', { candidate, mid });
>     });
> }
> 
> msg(data) {
>     if (data.type == 'offer' || data.type == 'answer') {
>         this.Peer.setRemoteDescription(data.sdp, data.type);
>     } else if (data.type == 'candidate') {
>         this.Peer.setRemoteCandidate(data.candidate, data.mid);
>     } else if (data.type == 'startRTC') {
>         // [Add an offered track here with this.Peer.addTrack(media)]
>         this.Peer.setLocalDescription();
>     }
> }
> ```

Oh, I looked at your libDatachannel and it's very, very simple and I wonder why WebrTC is so tedious.

Thank you very much, dear Paul.
 I have achieved it
server:
![image](https://user-images.githubusercontent.com/40012261/179928412-571dc924-b2f3-4d17-8a13-885ca28b8789.png)
pc:
![image](https://user-images.githubusercontent.com/40012261/179928852-bd7f04bd-d7bc-4e01-af7a-efcecfecd184.png)

**Comment by Canees** [comment]
What do I think I missed？GatheringState is't complete and track is't open
![image](https://user-images.githubusercontent.com/40012261/179953019-2ab984ab-2d59-414e-8c32-2fdebc1c8baf.png)
![image](https://user-images.githubusercontent.com/40012261/179953445-ce222cd9-6bf3-466a-84b9-3c8b65661bf4.png)

**Comment by Canees** [comment]
> What do I think I missed？GatheringState is't complete and track is't open ![image](https://user-images.githubusercontent.com/40012261/179953019-2ab984ab-2d59-414e-8c32-2fdebc1c8baf.png) ![image](https://user-images.githubusercontent.com/40012261/179953445-ce222cd9-6bf3-466a-84b9-3c8b65661bf4.png)

The PC is not in oniceconnectionstatechange send the answer
![image](https://user-images.githubusercontent.com/40012261/179958182-3c00a183-79fc-4520-a1c7-66a8450d1bd3.png)

track state is open,but pc GatheringState always  gathering, always no video, the track send buffer may be faulty
![image](https://user-images.githubusercontent.com/40012261/179958620-32ee02a4-7404-4f4a-86be-eb2ea7d2d493.png)

**Comment by kirianguiller** [comment]
I'm sorry to write a message in a closed issue, but this issue is the closest one to the question I currently have, and it might be more relevant to ask it here than to open issue.

I would like to send a video stream (from a [go2rtc](https://github.com/AlexxIT/go2rtc) server)  from a server (but more specifically a node-datachannel client) to another node-datachannel client. However, I don't understand how to send this stream.

In this current issue, we can see that @Canees set the Video track on the server, but I don't understand how this track is reading from another source.

Here is the relevant code snippet from @Canees :
```javascript
  this.socket.on('msg', data =>{
    // not showing the unrelevant part of the code
    if (data.type === 'startRTC') {
      // test video
      const video = new nodeDataChannel.Video('video', nodeDataChannel.Direction.SendOnly);
      video.addH264Codec(96);
      video.addSSRC(42, 'video-send');
      this.Peer.addTrack(video)
      this.Peer.setLocalDescription()
    }
  })
```

Is the ` video.addSSRC` method responsible for this ? How does it works ? I don't see this method being tested in the tests files, neither do I see it in [one of the 5 examples](https://github.com/murat-dogan/node-datachannel/tree/master/examples). Maybe this project could benefit by having an example showing how to use this library to send a video stream with datachannel. I would gladly help adding such an example once I will have figured how to make this works.

Thanks a lot for your help !
