### ISSUE TITLE
Add an audio/video RTP stream example?

### ISSUE THREAD

**Issue by Canees** [murat-dogan/node-datachannel#126]
I tried to use audio or video alone and it works, But I couldn't work with both of them.
Can it simultaneously transfer audio and video using GStreamer rptmux?
video:
            const video = new Video('video', 'SendOnly')
            video.addH264Codec(96)
            video.addSSRC(42, "video-send")
            const videoTrack = this.Peer.addTrack(video)
            const videoPort = 47788
            const videoArgs = [
                "libcamerasrc",
                "video/x-raw,width=320,height=240",
                "videoconvert",
                "queue",
                "x264enc tune=zerolatency bitrate=1000 key-int-max=30",
                "video/x-h264, profile=constrained-baseline",
                "rtph264pay pt=96 mtu=1200 ssrc=42",
                `udpsink host=127.0.0.1 port=${videoPort}`,
            ].join(" ! ").split(" ")
            this.videoChild = spawn("gst-launch-1.0", videoArgs)
            this.videoUDP = new UDP(videoPort, data => {
                if (!videoTrack.isOpen()) return
                videoTrack.sendMessageBinary(data)
            })

audio:
            const audio = new Audio('audio','SendOnly')
            audio.addOpusCodec(96)
            audio.addSSRC(42, "audio-send")
            const audioTrack = this.Peer.addTrack(audio)            
            const audioPort = 47789
            const audioArgs = [
                "audiotestsrc",
                "audio/x-raw,rate=8000,channels=1",
                "audioconvert",
                "queue",
                "opusenc",
                "rtpopuspay",
                `udpsink host=127.0.0.1 port=${audioPort}`,
            ].join(" ! ").split(" ")
            this.audioChild = spawn("gst-launch-1.0", audioArgs)
            this.audioUDP = new UDP(audioPort, data => {
                if (!audioTrack.isOpen()) return
                audioTrack.sendMessageBinary(data)
            }) 
error:
![image](https://user-images.githubusercontent.com/40012261/181701636-ed653ebb-b614-4d3d-817e-1dbf47c4111d.png)

gstreamer(But it doesn't work):
            const video = new Video('video', 'SendOnly')
            video.addH264Codec(96)
            video.addSSRC(42, "video-send")
            const videoTrack = this.Peer.addTrack(video)
            const videoPort = 47788            
            const videoArgs = [
                "libcamerasrc",
                "video/x-raw,width=320,height=240",
                "videoconvert",
                "queue",
                "x264enc tune=zerolatency bitrate=1000 key-int-max=30",   
                "video/x-h264, profile=constrained-baseline",
                "rtph264pay pt=96 mtu=1200 ssrc=42",                  
                "mux.sink_0",
                "audiotestsrc",
                "audio/x-raw,rate=8000,channels=1",
                "audioconvert",
                "queue",
                "opusenc",
                "rtpopuspay",
                "mux.sink_1",
                "rtpmux name=mux",
                `udpsink host=127.0.0.1 port=${videoPort}`,
            ].join(" ! ").split(" ")            
            this.videoChild = spawn("gst-launch-1.0", videoArgs)
            this.videoUDP = new UDP(videoPort, data => {
                if (!videoTrack.isOpen()) return
                videoTrack.sendMessageBinary(data)
            })
hi @paullouisageneau dear paull Do you have any advice?

**Comment by paullouisageneau** [comment]
You must use a different payload type and a different SSRC for each stream, for instance you could use 97 instead of 96 for audio payload type and 43 for audio SSRC, otherwise the browser can't demux the streams. You also need to set the proper parameters `pt=97 mtu=1200 ssrc=43` to `rtpopuspay`.

**Comment by Canees** [comment]
> You must use a different payload type and a different SSRC for each stream, for instance you could use 97 instead of 96 for audio payload type and 43 for audio SSRC, otherwise the browser can't demux the streams. You also need to set the proper parameters `pt=97 mtu=1200 ssrc=43` to `rtpopuspay`.

Thank you Paul，Audio setting PT =97 MTU =1200 SSRC =43 does not work，But the video is set to PT =97 and MTU =1200 and SSRC =43。
exp:
            const video = new Video('video', 'SendOnly')
            video.addH264Codec(97)
            video.addSSRC(43, "video-send")
            const videoTrack = this.Peer.addTrack(video)
            const videoPort = 47788
            const videoArgs = [
                "libcamerasrc",
                "video/x-raw,width=320,height=240",
                "videoconvert",
                "queue",
                "x264enc tune=zerolatency bitrate=1000 key-int-max=30",
                "video/x-h264, profile=constrained-baseline",
                "rtph264pay pt=97 mtu=1200 ssrc=43",
                `udpsink host=127.0.0.1 port=${videoPort}`,
            ].join(" ! ").split(" ")
            this.videoChild = spawn("gst-launch-1.0", videoArgs)
            this.videoUDP = new UDP(videoPort, data => {
                if (!videoTrack.isOpen()) return
                videoTrack.sendMessageBinary(data)
            })

            // -----------audio--------------
            const audio = new Audio('audio','SendOnly')
            audio.addOpusCodec(96)
            audio.addSSRC(42, "audio-send")
            const audioTrack = this.Peer.addTrack(audio)            
            const audioPort = 47789
            const audioArgs = [
                "audiotestsrc",
                "audio/x-raw,rate=8000,channels=1",
                "audioconvert",
                "queue",
                "opusenc",
                "rtpopuspay",
                `udpsink host=127.0.0.1 port=${audioPort}`,
            ].join(" ! ").split(" ")
            this.audioChild = spawn("gst-launch-1.0", audioArgs)
            this.audioUDP = new UDP(audioPort, data => {
                if (!audioTrack.isOpen()) return
                audioTrack.sendMessageBinary(data)
            }) 

One more quick question, do you know how GStreamer gets USB audio on the latest Raspi system, I tried a lot but it doesn't work?

**Comment by paullouisageneau** [comment]
> Thank you Paul，Audio setting PT =97 MTU =1200 SSRC =43 does not work，But the video is set to PT =97 and MTU =1200 and SSRC =43

That's surprising, `rtpopuspay` should support the parameters as shown [in the documentation](https://thiblahute.github.io/GStreamer-doc/rtp-1.0/rtpopuspay.html). In practice you only need to set `ssrc=43` if you assign h264 to payload type 97. You could also try to specify the parameters with capabilities: `rtpopuspay ! "application/x-rtp,payload=(int)97,clock-rate=(int)48000,ssrc=(uint)43"`

> One more quick question, do you know how GStreamer gets USB audio on the latest Raspi system, I tried a lot but it doesn't work?

The  `pulsesrc` source should work, but maybe something changed in recent versions that I'm not aware of.

**Comment by Canees** [comment]
> > Thank you Paul，Audio setting PT =97 MTU =1200 SSRC =43 does not work，But the video is set to PT =97 and MTU =1200 and SSRC =43
> 
> That's surprising, `rtpopuspay` should support the parameters as shown [in the documentation](https://thiblahute.github.io/GStreamer-doc/rtp-1.0/rtpopuspay.html). In practice you only need to set `ssrc=43` if you assign h264 to payload type 97. You could also try to specify the parameters with capabilities: `rtpopuspay ! "application/x-rtp,payload=(int)97,clock-rate=(int)48000,ssrc=(uint)43"`
> 
> > One more quick question, do you know how GStreamer gets USB audio on the latest Raspi system, I tried a lot but it doesn't work?
> 
> The `pulsesrc` source should work, but maybe something changed in recent versions that I'm not aware of.

ok,thank you paul
