### ISSUE TITLE
No video on the public network

### ISSUE THREAD

**Issue by Canees** [murat-dogan/node-datachannel#127]
The same code, the left is the public network, the right is the LAN.
It cannot work properly on the public network？
Is ICE not working properly？
@paullouisageneau  Do you have any good suggestions?
![image](https://user-images.githubusercontent.com/40012261/183342671-461f623b-0a61-49bd-91ee-e011c5b95677.png)
![image](https://user-images.githubusercontent.com/40012261/183357075-6bb2c6ef-429c-49dd-b078-ebe4644fea49.png)
![image](https://user-images.githubusercontent.com/40012261/183357239-d8248b73-8a87-4146-a79e-606bf19fe786.png)

**Comment by paullouisageneau** [comment]
Please describe your setup. Left and right on the first image both show a SDP description from a browser in the same private LAN context, the rest is about Violet STUN/TURN server and everything looks fine.

How is it related to node-datachannel? What exactly does not work? Please post the verbose log from node-datachannel to help debugging.

**Comment by Canees** [comment]
> Please describe your setup. Left and right on the first image both show a SDP description from a browser in the same private LAN context, the rest is about Violet STUN/TURN server and everything looks fine.
> 
> How is it related to node-datachannel? What exactly does not work? Please post the verbose log from node-datachannel to help debugging.

left: On the left are browsers opened in different segments
right: On the right is the browser opened in the same network segment as the service and browser
Yes, ICE seems to be working fine, GST is working fine,But browsers on different networks don't have video
     exp:
            const { PeerConnection, Video, Audio } = require('node-datachannel')
            // ------------video----------------
            const video = new Video('video', 'SendOnly')
            video.addH264Codec(96)
            video.addSSRC(42, "video-send")
            const videoTrack = this.Peer.addTrack(video)
            // -----------audio--------------
            const audio = new Audio('audio', 'SendOnly')
            audio.addOpusCodec(97)
            audio.addSSRC(43, "audio-send")
            const audioTrack = this.Peer.addTrack(audio)
            // ----------------
            Meadia.bullStart({ videoTrack, audioTrack })
            // -----------ice------
            this.Peer.setLocalDescription()


   fn：
    bullStart({ videoTrack, audioTrack }) {
        try {
            this.stop()
            if(!videoTrack && !audioTrack) throw 'track error'
            // ------------video----------------
            const videoPort = 47788
            const videoArgs = [
                "libcamerasrc",
                "video/x-raw,width=640,height=480",
                "videoconvert",
                "queue",
                "x264enc tune=zerolatency bitrate=1024 key-int-max=30 speed-preset=1",
                "video/x-h264, profile=constrained-baseline",
                "rtph264pay pt=96 mtu=1200 ssrc=42",
                `udpsink host=127.0.0.1 port=${videoPort}`,
            ].join(" ! ").split(" ")
            this.videoChild = spawn("gst-launch-1.0", videoArgs)
            this.videoUDP = new UDP(videoPort, data => {
                if (!videoTrack.isOpen()) return
                videoTrack.sendMessageBinary(data)
            })  
            // -----------audio--------------     
            const audioPort = 47789
            // alsamixer F6 defult:3-0
            // "alsasrc device=plughw:1,0",
            const audioArgs = [
                'alsasrc device=plughw:3,0',
                "audio/x-raw,rate=8000,channels=1",
                "audioconvert",
                "queue",
                "opusenc",
                "rtpopuspay",
                "application/x-rtp,payload=(int)97,clock-rate=(int)48000,ssrc=(uint)43",
                `udpsink host=127.0.0.1 port=${audioPort}`,
            ].join(" ! ").split(" ")
            this.audioChild = spawn("gst-launch-1.0", audioArgs)
            this.audioUDP = new UDP(audioPort, data => {
                if (!audioTrack.isOpen()) return
                audioTrack.sendMessageBinary(data)
            })                      
        } catch (error) {
            console.log('start meadia:', error)
        }

    }


Yes, I'll look at the debug days for Node-Datachannel later

**Comment by Canees** [comment]
When they are both on the LAN, Statechange is connected and video can be transmitted
![image](https://user-images.githubusercontent.com/40012261/183561919-b1d65dfd-eaa2-4876-b1ed-1467ec0ad78f.png)

**Comment by Canees** [comment]
It is already working properly and is an ICE candidate
