### ISSUE TITLE
Mysterious crash on simultaneous connections

### ISSUE THREAD

**Issue by harbu** [murat-dogan/node-datachannel#135]
Hello there!

We are occasionally seeing our software crash with the following fatal error when
- (a) the software (and hence library) is just starting up
- (b) there are multiple connections (like 100-1000) being established more or less the same time to the newly started app

```
FATAL ERROR:  Cannot read properties of undefined (reading 'forEach')
 1: 0xb00e10 node::Abort() [node]
 2: 0xa1823b node::FatalError(char const*, char const*) [node]
 3: 0xa18244  [node]
 4: 0xac882b napi_fatal_error [node]
 5: 0x7fb5fc310c70 Napi::CallbackScope::~CallbackScope() [/home/harbu/monorepo/node_modules/node-datachannel/build/Release/node_datachannel.node]
 6: 0x7fb5fc31edac ThreadSafeCallback::Impl::static_async_callback(uv_async_s*) [/home/harbu/monorepo/node_modules/node-datachannel/build/Release/node_datachannel.node]
 7: 0x155a806  [node]
 8: 0x156cc74  [node]
 9: 0x155b138 uv_run [node]
10: 0xa3dfe5 node::SpinEventLoop(node::Environment*) [node]
11: 0xb42e46 node::NodeMainInstance::Run(node::EnvSerializeInfo const*) [node]
12: 0xac4892 node::Start(int, char**) [node]
13: 0x7fb5ff6fb0b3 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
14: 0xa3bf3c  [node]
```

The error message itself looks like something that would happen in Javascript code (i.e. trying to call `forEach`  on an `undefined` object). However, after placing checks for this, e.g.,
```ts
if (someVar === undefined) {
                console.error("UNDEFINED DETECTED at trackerManager#start")
                process.exit(1)
}
someVar.forEach(() => { ... })
```

I haven't been able to find a place in our code where this would catch an undefined being invoked (it could happen at a higher level). The stack trace does seem to originate from the `node-datachannel` library. 

Do you have any idea if this is something that could be happening at the library level? Some race condition of sorts? Or is this more indicative of a bug on our side.

Any help greatly appreciated, Sincerely -Eric from Streamr

PS. We are using `"node-datachannel": "^0.3.4"`.

**Comment by murat-dogan** [comment]
Hi Eric,

At first glance, it seems related to something in js code that has been called as a callback from `node-datachannel`.
I have restructured all callbacks in V0.4.0 and should be compatible with your version.

Is it possible to test with v0.4.0?
What is your node version?
Is it possible to create a test environment, or maybe you can guide me?

**Comment by harbu** [comment]
Hey I could try that out. It seems like `0.4.0` hasn't been published yet to NPM https://www.npmjs.com/package/node-datachannel. Is it possible to publish it?

**Comment by murat-dogan** [comment]
Now it is published. That's weird, the release is created on 2 September, but somehow action didn't publish it.
I forced it now.

**Comment by murat-dogan** [comment]
Any update on this? @harbu

**Comment by harbu** [comment]
Not yet unfortunately. I'm working on something else at the moment, I'll get back probably at the end of this week or next week.

**Comment by harbu** [comment]
Hey this seemed to go away now. Thanks for the help!
