### ISSUE TITLE
Poor performance on media example

### ISSUE THREAD

**Issue by abacaj** [murat-dogan/node-datachannel#137]
Hello!
This library is great just trying to understand what the issue with the performance is.

When I playback the stream using **gstreamer I get < 5fps**

```
WARNING: from element /GstPipeline:pipeline0/GstAutoVideoSink:autovideosink0/GstD3D11VideoSink:autovideosink0-actual-sink-d3d11video: A lot of buffers are being dropped.
Additional debug info:
../libs/gst/base/gstbasesink.c(3145): gst_base_sink_is_too_late (): /GstPipeline:pipeline0/GstAutoVideoSink:autovideosink0/GstD3D11VideoSink:autovideosink0-actual-sink-d3d11video:
There may be a timestamping problem, or this computer is too slow.
0:00:42.2 / 99:99:99.
```

this is the stream from the browser:
```
        let media = await navigator.mediaDevices.getDisplayMedia({
          video: {
            minFrameRate: 30,
          },
        });
        media.getTracks().forEach((track) => {
          rtc.addTrack(track, media);
        });
```

this is the video track:
```
    const video = new datachannel.Video(
      'video',
      datachannel.Direction.RecvOnly,
    );
    video.addH264Codec(96);
    video.setBitrate(2000);

    const track = this.channel.addTrack(video);
    const session = new datachannel.RtcpReceivingSession();

    track.setMediaHandler(session);
    track.onMessage((msg) => {
      client.send(msg, 5000, '127.0.0.1', (err, n) => {
        if (err) console.log(err, n);
      });
    });
```

gst launch command:
```
 gst-launch-1.0 udpsrc address=127.0.0.1 port=5000 caps="application/x-rtp" ! queue ! rtph264depay ! video/x-h264,stream-format=byte-stream ! queue ! avdec_h264 ! queue ! autovideosink
```

**EDIT**
cpu usage< 5%
gpu usage < 5%

![image](https://user-images.githubusercontent.com/7272343/198935782-9451cfec-ad1d-4bb5-8b39-c10c1d733354.png)

any ideas?

**Comment by Canees** [comment]
> Hello! This library is great just trying to understand what the issue with the performance is.
> 
> When I playback the stream using **gstreamer I get < 5fps**
> 
> ```
> WARNING: from element /GstPipeline:pipeline0/GstAutoVideoSink:autovideosink0/GstD3D11VideoSink:autovideosink0-actual-sink-d3d11video: A lot of buffers are being dropped.
> Additional debug info:
> ../libs/gst/base/gstbasesink.c(3145): gst_base_sink_is_too_late (): /GstPipeline:pipeline0/GstAutoVideoSink:autovideosink0/GstD3D11VideoSink:autovideosink0-actual-sink-d3d11video:
> There may be a timestamping problem, or this computer is too slow.
> 0:00:42.2 / 99:99:99.
> ```
> 
> this is the stream from the browser:
> 
> ```
>         let media = await navigator.mediaDevices.getDisplayMedia({
>           video: {
>             minFrameRate: 30,
>           },
>         });
>         media.getTracks().forEach((track) => {
>           rtc.addTrack(track, media);
>         });
> ```
> 
> this is the video track:
> 
> ```
>     const video = new datachannel.Video(
>       'video',
>       datachannel.Direction.RecvOnly,
>     );
>     video.addH264Codec(96);
>     video.setBitrate(2000);
> 
>     const track = this.channel.addTrack(video);
>     const session = new datachannel.RtcpReceivingSession();
> 
>     track.setMediaHandler(session);
>     track.onMessage((msg) => {
>       client.send(msg, 5000, '127.0.0.1', (err, n) => {
>         if (err) console.log(err, n);
>       });
>     });
> ```
> 
> gst launch command:
> 
> ```
>  gst-launch-1.0 udpsrc address=127.0.0.1 port=5000 caps="application/x-rtp" ! queue ! rtph264depay ! video/x-h264,stream-format=byte-stream ! queue ! avdec_h264 ! queue ! autovideosink
> ```
> 
> **EDIT** cpu usage< 5% gpu usage < 5%
> 
> ![image](https://user-images.githubusercontent.com/7272343/198935782-9451cfec-ad1d-4bb5-8b39-c10c1d733354.png)
> 
> any ideas?

I think it is the cause of gst，You can refer to it : https://github.com/murat-dogan/node-datachannel/pull/125/files,,,video/x-raw,width=320,height=240

**Comment by murat-dogan** [comment]
Hi @abacaj ,

I have tested the example code and worked well.
Could you please also test it?

**Comment by murat-dogan** [comment]
Can I close this?

**Comment by abacaj** [comment]
Thank you, issue was on my side not library.
