### ISSUE TITLE
Prebuilt binaries don't install on Windows as of v0.3.6

### ISSUE THREAD

**Issue by dguenther** [murat-dogan/node-datachannel#138]
I tested an npm project with node-datachannel 0.3.6 on a clean installation of Windows, and it fails with missing CMake, which I assume means it's trying to build node-datachannel from source rather than installing the prebuilt binaries:

```
PS C:\Users\Administrator\ndc> npm install
npm ERR! code 2
npm ERR! path C:\Users\Administrator\ndc\node_modules\node-datachannel
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c prebuild-install || (npm install --ignore-scripts && npm run _prebuild)
npm ERR! added 600 packages, removed 1 package, and audited 658 packages in 31s
npm ERR!
npm ERR! 67 packages are looking for funding
npm ERR!   run `npm fund` for details
npm ERR!
npm ERR! 4 high severity vulnerabilities
npm ERR!
npm ERR! To address all issues (including breaking changes), run:
npm ERR!   npm audit fix --force
npm ERR!
npm ERR! Run `npm audit` for details.
npm ERR!
npm ERR! > node-datachannel@0.3.6 _prebuild
npm ERR! > prebuild --backend cmake-js
npm ERR!
npm ERR! [
npm ERR!   'C:\\Users\\Administrator\\scoop\\apps\\volta\\current\\appdata\\tools\\image\\node\\18.12.0\\node.exe',
npm ERR!   'C:\\Users\\Administrator\\ndc\\node_modules\\node-datachannel\\node_modules\\cmake-js\\bin\\cmake-js',
npm ERR!   'rebuild',
npm ERR!   '--runtime-version=18.12.0',
npm ERR!   '--arch=x64',
npm ERR!   '--runtime=node'
npm ERR! ]
npm ERR! prebuild-install WARN install The specified module could not be found.
npm ERR! prebuild-install WARN install \\?\C:\Users\Administrator\ndc\node_modules\node-datachannel\build\Release\node_datachannel.node
npm ERR! npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm ERR! npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! prebuild info begin Prebuild version 11.0.4
npm ERR! prebuild info build Preparing to prebuild node-datachannel@0.3.6 for node 18.12.0 on win32-x64 using cmake-js
npm ERR! ERR! OMG CMake is not installed. Install CMake.
npm ERR! ERR! OMG CMake is not installed. Install CMake.
npm ERR! prebuild ERR! build Error: Failed to build cmake with exit code 1
npm ERR! prebuild ERR! build     at ChildProcess.<anonymous> (C:\Users\Administrator\ndc\node_modules\node-datachannel\node_modules\prebuild\cmakebuild.js:32:19)
npm ERR! prebuild ERR! build     at ChildProcess.emit (node:events:513:28)
npm ERR! prebuild ERR! build     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

When installing v0.3.5 on the same machine, it installs without an error:

```
PS C:\Users\Administrator\ndc> npm install

added 1 package, and audited 60 packages in 3s

7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

I tested this with Node 16 and Node 18.

**Comment by murat-dogan** [comment]
Hi,

I have just tested with node v16 & v18, I didn't get any error.

I am testing on Windows 10, what is different?

**Comment by murat-dogan** [comment]
I have also tested to install `@ironfish/sdk` v0.0.27 and had no errors (node v16, windows 10 x64, node-datachannel v0.3.6)

**Comment by dguenther** [comment]
Do you have CMake installed on your Windows machine already? If you have Windows 10 Pro, an easy way to ensure you have a clean environment is by using Windows Sandbox: https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview

If so, I wonder if it might have to do with the version of Windows... I tested on an AWS machine, Windows Server Version 21H2 (OS 20348.1129). I'll see if I can start up a Windows 10 environment in a VM today to test.

**Comment by murat-dogan** [comment]
I don’t have CMake installed. I have checked that also. 

I could try sandbox tomorrow.

**Comment by dguenther** [comment]
Reproduced this on Windows 11 x64 in a sandbox (Windows Version 21H2 (OS Build 22000.1098). All I have installed is Volta, Node 16, and the Visual C++ redistributable. I'll see if I can set up a Windows 10 VM tomorrow.

**Comment by murat-dogan** [comment]
I have found the problem.
The problem is about OpenSSL lib.
V0.3.6 needs OpenSSL as locally installed (Dynamically linked)

While working to support Mac M1 builds, it has been accidentally converted to dynamic linking.
I have fixed it and released new binaries for v0.4.0

I have added a note for v0.3.6 but have not released new binaries.

Thank you for reporting.

**Comment by dguenther** [comment]
I'm still seeing the same issue, but I wonder if it's related to `prebuild-install` somehow. I noticed when checking out the repository and changing the `install` script to just `prebuild-install`, then running `npm install`, I get this warning:

```
prebuild-install WARN install The specified module could not be found.
prebuild-install WARN install \\?\C:\Users\Administrator\node-datachannel\build\Release\node_datachannel.node
```

It actually downloads the module correctly as I can see it in the `build\Release\node_datachannel.node` folder, but doesn't detect it for some reason. Also, if instead of running `npm install`, I run `node_modules\.bin\prebuild-install` directly, it works as expected.

**Comment by dguenther** [comment]
Hmm, it's a caching problem. I'll do a bit more testing

**Comment by dguenther** [comment]
Yep, looks like `prebuild-install` caches based on the URL, and the URL didn't change in this case. So if someone has previously attempted to install 0.4.0, it'll cache the non-working binary in `npm-cache` and fail the install. I don't think there's really a way around this without doing a new release, so I think this is good to close, thanks!

**Comment by murat-dogan** [comment]
Thanks for info
