### ISSUE TITLE
Where to host a webrtc server ?

### ISSUE THREAD

**Issue by Daavidaviid** [murat-dogan/node-datachannel#139]
Is it possible on google cloud ? Does it allow udp ?

**Comment by murat-dogan** [comment]
Hi
I guess you mean signaling or TURN server.
Yes you can use google cloud, it should not be a problem.

**Comment by Daavidaviid** [comment]
Hey,
Thanks for your answer. I should have done my homework and read the webrtc specs completely first. I think my question is more, is it possible to host a client from this example :
https://github.com/murat-dogan/node-datachannel/tree/master/examples/client-server

Using a solution like Google App Engine ?

I'd like to create an authoritative server (it would be a webrtc client in this case) exchanging data with web browser clients through udp.

That's a possible use case for this node-datachannel, right ?

**Comment by murat-dogan** [comment]
I don’t have info about Google app engine, but yes you can run a client inside a Google cloud vm.

If I understand your case correctly then you don’t need such library. 
Why don’t you think to use plain https?

**Comment by Daavidaviid** [comment]
> I don’t have info about Google app engine, but yes you can run a client inside a Google cloud vm.
> 
> 
> 
> If I understand your case correctly then you don’t need such library. 
> 
> Why don’t you think to use plain https?
> 
> 

I'd like to do real time communication between a server and a web browser with udp ideally

**Comment by murat-dogan** [comment]
Actually webrtc is mainly used for client-client communication.
In your case yes could do the work but the only reason you are using webrtc will be udp.

If you have too many clients you should have a mechanism to manage this on server side.

**Comment by murat-dogan** [comment]
I am closing this. If you need further help please re-open it
