### ISSUE TITLE
Compatibility with electron on Windows? Strange behavior with cmd and git-bash

### ISSUE THREAD

**Issue by ci010** [murat-dogan/node-datachannel#142]
The module cannot be load in electron windows in the most cast.

But! If you have git-bash, all the electron processes (including the original git bash and child process) spawned from the git bash can correctly load the module. This is a really interesting behavior...

### Repro of module cannot loaded

Repro repo: https://github.com/ci010/repro-demo

Repro steps:
1. Clone repo and install the dependencies
2. Run `npm start`. You will see an error dialog saying the module not found
```
App threw an error during load
Error: The specified module could not be found.
```

#### Note

I tried to directly use `process.dlopen`, and the result is the same.

### Repro of module can be loaded

Same repo: https://github.com/ci010/repro-demo

1. Same steps to clone and install
2. Open git-bash.exe (in any terminal). Run `npm start` in git-bash.
3. You will see the module is correctly printed.

#### Note
The sub-process opened by the git-bash can also work.
For example, you can open a cmd by gitbash, and in that cmd, you can correctly load the module in electron.
Same for VSCode...

### Some clue

Currently, I guess this is caused by the different PATH between the cmd and the git-bash. The git-bash will have some mingw64 bin in PATH.

I guess some mingw64 dlls are required?

**Comment by murat-dogan** [comment]
Seems like a path format problem.
Could you please change the path in index.js and try again.

**Comment by ci010** [comment]
Some update

I found the lib is trying to load several dll under mingw64. After I put these dll under the electron exe directory, it works.

![image](https://user-images.githubusercontent.com/8425057/205054218-380bfc12-57ad-485f-bd50-fae163745b15.png)

**Comment by murat-dogan** [comment]
Hi,
OpenSSLis linked statically actually. 
Why is it searching these DLLs?

Could these DLLs be needed by electron?

**Comment by murat-dogan** [comment]
Hi,

Any news on this?

**Comment by ci010** [comment]
> Hi,
> 
> Any news on this?

These are not imported by electron. We can verify it by the repro demo to prove that. By comment out the node-datachannel, these libs won't be loaded.

**Comment by murat-dogan** [comment]
Hello,

I have just released a dev version with N-API compatibility and an electron demo project.

Could you please check it or test it with your project?
Thanks

**Comment by ci010** [comment]
> Hello,
> 
> I have just released a dev version with N-API compatibility and an electron demo project.
> 
> Could you please check it or test it with your project? Thanks

I tried on my dev environment, and it LGTM now. I need to take time to test it on production build (built binary).

**Comment by ci010** [comment]
Closed due to tested on production. Not repro.
