### ISSUE TITLE
Support for setting the `libdatachannel` `bindAddress` option on the `rtc::Configuration` object

### ISSUE THREAD

**Issue by bcjordan** [murat-dogan/node-datachannel#143]
Thanks for this library, super efficient/simple transport for web games! I'm looking to use node-datachannel as part of a .io game building on the wonderful geckos.io library.

I'm looking to deploy this on Fly.io (nice infra tool to just define a Dockerfile + deploy it to various regions), which supports UDP but requires a specific `bindAddress` (host that's not `127.0.0.1` or `*` etc.) in order for their global routing system to work.

It seems the best way to approach this would be patching `node-datachannel` to set the `libdatachannel` `bindAddress` option on its `rtc::Configuration` object here: https://github.com/murat-dogan/node-datachannel/blob/e16669283e0f0f176a2515c415855d01eb886299/src/peer-connection-wrapper.cpp#L83

**Comment by murat-dogan** [comment]
Hi,

Thank you for your kind words & reporting this.
Fix applied with #144 
It will be released with the new version.(v0.4.1)

**Comment by bcjordan** [comment]
@murat-dogan amazing, thank you! Curious if any idea when 0.4.1 may be slated for? No rush, able to run geckos.io upstream giving npm this commit's git hash, but will likely want to wait for 0.4.1 to merge it.

**Comment by murat-dogan** [comment]
I guess it will not take too much time to prepare the release. A week maybe.
