### ISSUE TITLE
usage as polyfill

### ISSUE THREAD

**Issue by ThaUnknown** [murat-dogan/node-datachannel#145]
I'd like to use this library as a 1:1 polyfill of the browser [WebRTC API](https://devdocs.io/dom/rtcpeerconnection), however it seems to lack a few events like negotationneeded, iceconnectionstatechange and icecandidateerror, would it be possible to use this library as a polyfill?

**Comment by murat-dogan** [comment]
Hi,
I guess this could be an issue for the upstream library libdatachannel.
Could you please open an issue on libdatachannel?

**Comment by ThaUnknown** [comment]
it's not really related to libdatachannel, libdatachannel is a C++ implementation, this is bridging that to JS, and the question is to make the JS version w3c spec compliant

there's no reason for a C++ library to follow a JS spec structure, but there is a reason for a JS library to follow a JS spec structure

**Comment by murat-dogan** [comment]
I see.
So you mean the lack part is not related to C++ code. 
All of them could be generated from JS side itself. (In this case events)
Right?

**Comment by ThaUnknown** [comment]
yup, it would require a significant restructure, and manual state management, but it would mean this library would be an insanely high performance drop-in replacement for web's WebRTC, meaning WebRTC packages made for browsers would work on node just fine, for example [simple-peer](https://www.npmjs.com/package/simple-peer)

**Comment by murat-dogan** [comment]
Good point.

**Comment by ThaUnknown** [comment]
> Good point.

if you ever go for this massive undertaking, I recomment the `web-platform-tests` repository to test compatibility of your WebRTC implementation, notably packages like `wrtc` already do it, see [this link](https://github.com/node-webrtc/node-webrtc/tree/develop/test/web-platform-tests), tho wrtc is laughably slow

**Comment by PodaruDragos** [comment]
how would someone even start this ? 
this seems incredibly complicated and time consuming.

Can this be done incremental ? at a very very slow pace ?

**Comment by ThaUnknown** [comment]
you can do this incrementally, I'd do it like this:
- set up web platform test for webrtc
- go to the webrtc documentation for web, say mdn, or if you want to be more thorough the w3c spec
- start creating each class, its methods and properties, starting with ones that libdatachannel exposes
- test each method and property
- implement custom functionality for methods and properties that are missing

Overall the first thing that needs to be done is a skeleton of each webrtc class and method they have, even if blank, and add each functionality incrementally

**Comment by murat-dogan** [comment]
Actually, I have this issue in mind. 
But the problem is I am extremely busy at this period and I don't know when I could have some free time.

**Comment by ThaUnknown** [comment]
> Actually, I have this issue in mind. But the problem is I am extremely busy at this period and I don't know when I could have some free time.

If you want to, make a branch for the polyfill, I'll try helping with some initial structure

**Comment by murat-dogan** [comment]
Thanks!
I have created the branch polyfill for this issue.
https://github.com/murat-dogan/node-datachannel/tree/polyfill

**Comment by ThaUnknown** [comment]
@murat-dogan #160 I've implemented basic types and skeletons, feel free to move the types to different files.

Next up is either adding functionality to the skeletons, or adding web platform tests, so you can test if the functionality is spec compliant.

Once this package adds the polyfills, is there really any need to keeping the other js interfaces you made? If not then this definetly should be a major version release.

**Comment by alfredomariamilano** [comment]
I second this. It would be great for it to be able to replace wrtc in simple-peer

**Comment by ThaUnknown** [comment]
https://github.com/murat-dogan/node-datachannel/commits/polyfill exists, but no work on it has been done since I created the initial skeleton structure, but I think the important thing is this module is compatible with `libdatachannel` which is by far the best native code implementation of WebRTC i know

**Comment by murat-dogan** [comment]
Hello,
@ThaUnknown is right, he implemented the basic structure.
I am aware of this feature and I really want to implement it. But the problem is I am on a big project and I have nearly no time. 

I will try to find some free time for it but when I really don’t know yet. Any help will be appreciated. Please feel free to create PRs. 

Thanks

**Comment by ThaUnknown** [comment]
I'm also bussy as shit, between work, uni and my own projects, I don't see myself contributing much more to this

**Comment by achingbrain** [comment]
I've created a partial polyfill (only the parts of the spec API I'm using) in the `@libp2p/webrtc` module based on the work in the polyfill branch here - it's TypeScript so a bit more work to port over, or this module could switch to TS.

- [RTCPeerConnection](https://github.com/libp2p/js-libp2p/blob/master/packages/transport-webrtc/src/webrtc/rtc-peer-connection.ts)
- [RTCDataChannel](https://github.com/libp2p/js-libp2p/blob/master/packages/transport-webrtc/src/webrtc/rtc-data-channel.ts)
- [RTCIceCandidate](https://github.com/libp2p/js-libp2p/blob/master/packages/transport-webrtc/src/webrtc/rtc-ice-candidate.ts)
- [RTCSessionDescription](https://github.com/libp2p/js-libp2p/blob/master/packages/transport-webrtc/src/webrtc/rtc-session-description.ts)
- [RTC events](https://github.com/libp2p/js-libp2p/blob/master/packages/transport-webrtc/src/webrtc/rtc-events.ts)

The are classes are named differently from the spec API types in `lib.dom.d` (bundled with TypeScript) as masking the interface names gets fiddly.

Not everything maps over cleanly so I think there will be some PRs necessary to lib-datachannel to get 100% of the W3C spec implemented.

Anyway feel free to use the code, it might help things along a bit.  If this module switched to TS I'd be happy to PR my changes in.

**Comment by ThaUnknown** [comment]
>  classes are named differently
see that's not an option for a polyfill, for a ponyfill maybe

**Comment by achingbrain** [comment]
Yep, agreed.

**Comment by ThaUnknown** [comment]
anyways I didn't do TS as we can simply specify that these are "native" webrtc functions, and most IDE's that integrate web api definitions will do that just fine, so we could even ditch the index.d.ts file in theory

**Comment by ThaUnknown** [comment]
do you know how does it fair with webplatformtests for webrtc?

**Comment by murat-dogan** [comment]
Thanks @achingbrain 

I have already started to work on it, and I will check your code also. I don’t know how long it will take though.

i agree with @ThaUnknown  js seems better choice.

**Comment by ThaUnknown** [comment]
@murat-dogan I've implemented his code, and changed how the polyfill handles types, which makes it way easier for us to maintain in the future, added stricter type checking on our JS too using @ts-check, I haven't verified how the functions behave in regards to the w3c standard tho, as we havent implemented web platform tests https://github.com/murat-dogan/node-datachannel/pull/173

i hope its not too conflicting with your changes

**Comment by murat-dogan** [comment]
Hello all,

I have finished the basic work for polyfills. Thank you @ThaUnknown  and @achingbrain 

Generic test :  `$> node test/polyfill-connectivity.js`
simple-peer test: 
```
$> cd cd test/simple-peer-test/
$> npm i 
$> node test.js
```

Both tests are working now. This will be a good start I guess.

**Comment by ThaUnknown** [comment]
@murat-dogan this is great, I have some questions tho, why did you remove the JSDoc and TSCheck? also why do you now implement the webrtc types yourself instead of using the global ones? this can potentially cause issues as they might not be the same as the global ones. TSCheck is also good for development and checking.

Also error types, why was TypeError dropped? this matters for web platform tests, which will fail without changes like these

**Comment by murat-dogan** [comment]
Hi @ThaUnknown ,

I am sure TSCheck and JSDoc are great tools but they are not part of the development process of this project. We are already using only .d.ts files for typings.

Actually I am also using global definitions like
```
/// <reference lib="dom" />

export default class _RTCPeerConnection extends EventTarget implements RTCPeerConnection {
```
Here RTCPeerConnection is from DOM.

About TypeError, I dont know why but sometimes simple-peer called the constuctor with empty values. This is now for testing not final codes, so please test and write back what you see.

As you may see I have prepared web platform tests in test/wpt.js
I dont know if I will have time to continue this work though.

**Comment by ThaUnknown** [comment]
@murat-dogan I still can't agree with the types implementation for this, because it will keep causing issues where functions, fields and return values aren't inline with their W3C specification, and it already shows with the changes you've made

that's however your choice, it simply makes more work for you

I made a PR with some required changes for this to behave more like the W3C WebRTC spec: https://github.com/murat-dogan/node-datachannel/pull/177

If you want this to be a polyfill, you need to be more strict with the changes you make, like the changes here:
https://github.com/murat-dogan/node-datachannel/commit/4a0299e766bd99b1af6d3ce6b62619db0ef6b25d#diff-48d7fab52294f4a4b83ef76ac2f013962542e419356f1d8df3f9a6940f8f86a8R8-R38
this causes a lot of issues, because this is no longer inline with the spec, and it inputs values when it shouldnt, additionally the `=` line split will never occur, as according to the spec this is what an ICE candidate should look like:
`a=candidate:4234997325 1 udp 2043278322 192.168.0.56 6502 typ srflx raddr 192.168.2.77 rport 32768 generation 0`

critique aside, this is already x3 faster than `wrtc` while using less CPU, except for the errors caused by it not being inline with the W3C spec

**Comment by ThaUnknown** [comment]
also I wanted to [at least partially] polyfill video and audio tracks, but it seems undocumented?

**Comment by murat-dogan** [comment]
https://github.com/murat-dogan/node-datachannel/releases/tag/v0.5.0-dev

I have just released a dev version including polyfill changes until now.
Feedback is welcomed.

Thank you to all.

**Comment by ThaUnknown** [comment]
I don't see them?

**Comment by murat-dogan** [comment]
Name was tagged from last week.
I recreated it. Now it is fixed.

**Comment by luisfonsivevo** [comment]
We're using this polyfill and it's working great. The only problem I've encountered is that `RTCSctpTransport` is not implemented, so I need to patch the prototype:

```
delete RTCPeerConnection.prototype.sctp;
RTCPeerConnection.prototype.sctp = { maxMessageSize: 256 * 1024 };
```

which comes from here: https://github.com/paullouisageneau/libdatachannel/blob/09963b818ffbf12fce3db014fc337da4f3780a47/src/impl/internals.hpp#L41

To implement the getter, I think libdatachannel's `PeerConnection::remoteMaxMessageSize()` can be used (it returns the min of the local and remote message sizes): https://github.com/paullouisageneau/libdatachannel/blob/09963b818ffbf12fce3db014fc337da4f3780a47/src/impl/peerconnection.cpp#L103C24-L103C44

**Comment by ThaUnknown** [comment]
i do it via
```js
  get maxMessageSize () {
    for (const channel of this.#dataChannels) {
      const maxSize = channel.maxMessageSize
      if (maxSize) return maxSize
    }
    for (const track of this.#tracks) {
      const maxSize = track.maxMessageSize()
      if (maxSize) return maxSize
    }
    return null
  }
```
as it might change based on network conditions
https://github.com/ThaUnknown/webrtc-polyfill/blob/main/lib/RTCPeerConnection.js#L319-L329
but exposing bindings for it is probably a better idea

**Comment by paullouisageneau** [comment]
> To implement the getter, I think libdatachannel's `PeerConnection::remoteMaxMessageSize()` can be used (it returns the min of the local and remote message sizes): https://github.com/paullouisageneau/libdatachannel/blob/09963b818ffbf12fce3db014fc337da4f3780a47/src/impl/peerconnection.cpp#L103C24-L103C44

Yes, libdatachannel actually has the getter exposed on `DataChannel`: https://github.com/paullouisageneau/libdatachannel/blob/5105eda25ec386ef92353eebefcde250360a6c1a/include/rtc/datachannel.hpp#L40

@ThaUnknown You shouldn't do that. Tracks are entirely different and will basically return a maximum UDP packet size, so something very small and unrelated to SCTP message size (which will never change according to network, it's negotiated between peers via SDP).

You should do something like:
```js
 get maxMessageSize () {
    if(this.#dataChannels.length == 0)
      return null

    return this.#dataChannels[0].maxMessageSize
}
```
But indeed exposing a proper getter would be better.

**Comment by luisfonsivevo** [comment]
> Yes, libdatachannel actually has the getter exposed on `DataChannel`: https://github.com/paullouisageneau/libdatachannel/blob/5105eda25ec386ef92353eebefcde250360a6c1a/include/rtc/datachannel.hpp#L40

Would `PeerConnection::remoteMaxMessageSize()` equate to the min of all active `DataChannel`s in that case?

**Comment by paullouisageneau** [comment]
> Would `PeerConnection::remoteMaxMessageSize()` equate to the min of all active `DataChannel`s in that case?

All data channels on the peer connection have the same max message size, it's actually read from `impl::PeerConnection::remoteMaxMessageSize()` internally (which is currently not exposed).

**Comment by murat-dogan** [comment]
@luisfonsivevo 

I have implemented (at least partially) transports.
I am updating binaries for 0.5.0-dev (be aware of local caches!, ~/.npm/_prebuilds/)
Please use master as the latest source, not updating the tag and npm.

**Comment by murat-dogan** [comment]
I have just released v0.5.0 with the latest changes.

**Comment by luisfonsivevo** [comment]
Just tried `maxMessageSize` and it's working. Thanks!
I think this `console.log` line was left in by mistake: https://github.com/murat-dogan/node-datachannel/blob/5528f2f4a355457fdee3fb416f67d6176681e0ee/polyfill/RTCIceTransport.js#L21

**Comment by murat-dogan** [comment]
Could you please check examples folder?
There is an example of basic usage.
What is the difference?

**Comment by mikey0000** [comment]
Well I'm not sure because I followed the example.

30/11/2023 8:19:03 pm Murat Doğan ***@***.***>:

**Comment by mikey0000** [comment]
Oh this might be the difference, electron. Anyway I'll try and create a repro project

30/11/2023 8:19:03 pm Murat Doğan ***@***.***>:
