### ISSUE TITLE
Android termux build issue

### ISSUE THREAD

**Issue by jowparks** [murat-dogan/node-datachannel#153]
## Unable to install in termux
I was trying to build `node-datachannel` in termux and I was getting an error.

```bash
[ 19%] Building C object _deps/libdatachannel-build/deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_indata.c.o
/data/data/com.termux/files/home/ironfish/node_modules/node-datachannel/build/_deps/libdatachannel-src/deps/usrsctp/usrsctplib/netinet/sctp_indata.c:3323:6: error: variable 'tot_retrans' set but not used [-Werror,-Wunused-but-set-variable]
        int tot_retrans = 0;
            ^
1 error generated.#] / reify:node-datachannel: timing reify:createSparse Completed in 35ms
```

I also tried adding `CFLAGS=-Wno-error` before my `npm install node-datachannel`, the flag doesn't seem to propagate to the underlying cmake system as I get the same error.

## Underlying issue

I ran across this PR and I was surprised my build wasn't working:
https://github.com/murat-dogan/node-datachannel/pull/152/files

The PR above checkes `CMAKE_HOST_SYSTEM_NAME` if it is set to `Android`.

I googled around for `CMAKE_HOST_SYSTEM_NAME` and it seems to derive its value from `uname -s`:
https://cmake.org/cmake/help/latest/variable/CMAKE_HOST_SYSTEM_NAME.html

When I run this in termux, I get `Linux`, not `Android`. Am I looking at something wrong?

This seems like a relevant change on Feb 12th in termux:
https://github.com/termux/termux-packages/blob/master/packages/git/config.mak.uname.patch

**Comment by murat-dogan** [comment]
Hi,

We need to identify termux somehow.
Is it possible for you to add CMAKE_SYSTEM_NAME as Android

Please check install-nice script as an example how to pass definition to the cmake

**Comment by murat-dogan** [comment]
Any update on this?
