### ISSUE TITLE
v0.4.1 prebuild issue

### ISSUE THREAD

**Issue by pimterry** [murat-dogan/node-datachannel#155]
Hi,

I'm seeing some strange crashes for some of my users who are trying to load node-datachannel on Mac, after updating to v0.4.1 (v0.4.0 seems to work fine). This is all using the standard prebuilt binaries for everything.

The errors look like this:

```
Error: dlopen(/Users/$USER/.local/share/httptoolkit-server/client/1.12.4/node_modules/node-datachannel/build/Release/node_datachannel.node,
     1): Symbol not found: 
    __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
      Referenced from: 
    /Users/$USER/.local/share/httptoolkit-server/client/1.12.4/node_modules/node-datachannel/build/Release/node_datachannel.node (which was built for Mac OS X 12.0)
      Expected in: /usr/lib/libc++.1.dylib

    Code: ERR_DLOPEN_FAILED
```

This doesn't seem to affect all users, but enough to cause problems. From a quick sample, it looks like affected users are using Mac 11, so the "built for Mac OS X 12.0" message above seems like a likely culprit.

Any idea what's happening here? Did the build process for v0.4.1 change so that prebuilds now only support Mac v12+?

**Comment by murat-dogan** [comment]
Hi @pimterry ,

I made a quick check but could not see any major change.
The only thing I guess is; we are using `macos-latest` as mac build pc version on Github actions.
This could be changed from 11 to 12 meanwhile.

I have created a new branch & created new binaries with `macos-11`
Could you please download and install the binaries manually? 
https://github.com/murat-dogan/node-datachannel/releases/tag/v0.4.2-dev

And I don't know, if this works, how this will affect macos-12 users.

**Comment by pimterry** [comment]
> The only thing I guess is; we are using macos-latest as mac build pc version on Github actions.

Ah, yes, that will definitely be it, you're totally right. v0.4.0 was built & released in September 2022, then in October 2022 macos-latest [switched over](https://github.blog/changelog/2022-10-03-github-actions-jobs-running-on-macos-latest-are-now-running-on-macos-12/) to v12, and I can see in the [v0.4.1 build logs](https://github.com/murat-dogan/node-datachannel/actions/runs/3857184461/jobs/6574285011) (under 'Set up job', 'Operating system') that it did run with v12.

This makes a lot of sense, and also explains why my own tests didn't hit it - I'm also using `macos-latest`. Doh. I'll fix that on my end too so I spot this in my own setup earlier.

> I have created a new branch & created new binaries with macos-11
> Could you please download and install the binaries manually?

I will test this out tomorrow and let you know. I have a new-ish M1 Mac mini for testing that uses v12, but also I have an old Macbook somewhere which I think is still on v11, so I should be able to check both!

**Comment by pimterry** [comment]
Tested - that v0.4.2-dev release seems to work everywhere for me now! Great work, thanks @murat-dogan :+1:

**Comment by murat-dogan** [comment]
Super. Thank you for your feedback. 
I will update libdatachannel and release v0.4.2
