### ISSUE TITLE
Clarity on "high" buffer thresholds

### ISSUE THREAD

**Issue by harbu** [murat-dogan/node-datachannel#159]
Hi Murat,

In the library we have methods `dataChannel#setBufferedAmountLowThreshold` and `dataChannel#onBufferedAmountLow` to control and observe the low watermark of send buffer.

I was wondering what is the maximum (or high watermark) of the same buffer?

I'm working on a high-throughput project where the amount of data being sent is very spiky in nature. I've noticed that `dataChannel#send` returns `false` quite a lot even when the buffer (as obtained from `dataChannel#bufferedAmount()`) is well below 512kb or so. Calling `dataChannel#send` on the same message repeatedly until eventually it returns `true` works, but I was wondering if there is something as a user I can do to prevent `dataChannel#send` from returning `false` that often? E.g. we have implemented high watermark buffering user-side. I was wondering if I pluck in the correct limit that matches this library's limit then maybe send would return `true` more often.

Sincerely,- Eric from Streamr

**Comment by murat-dogan** [comment]
Hello Eric,

The send function is here;
https://github.com/paullouisageneau/libdatachannel/blob/c0f4203c02d5746cbaaaab4fd6f5b90431def38d/src/impl/sctptransport.cpp#L372

There is no limit for buffering. 
SCTP has but `libdatachannel` does not. 
And you can change the buffer limits of SCTP by using `node-datachannel` api.

The return value of send function is related to buffering.
- If the message could be delivered without buffering, then it returns true
- If the message needs to be buffered then it returns false

For performance please check https://github.com/murat-dogan/node-datachannel/issues/34

And also please check examples/client-server/client-benchmark.js

I made lots of tests in the past and I can say that library's performance is really good.

Regards,
Murat

**Comment by harbu** [comment]
Firstly, big thanks for your response and your time.

> And you can change the buffer limits of SCTP by using node-datachannel api.

I'm guessing this is the setting to adjust: https://github.com/murat-dogan/node-datachannel/blob/master/lib/index.d.ts#L11. I'll have a look at this.

>The return value of send function is related to buffering.
> If the message could be delivered without buffering, then it returns true
> If the message needs to be buffered then it returns false

Interesting. Just to make sure I'm understanding this correctly: if it returns false, do I have to call `dataChannel.send`  myself later again? Or does it mean that it got buffered by the library and will be sent eventually and I should **not** call `dataChannel.send` again to avoid sending duplicate message?

**Comment by murat-dogan** [comment]
No, you don’t need to call it again. Library will handle it. 
Also if buffer is low, messages sent, you will get a callback.
Please see benchmark example.

**Comment by harbu** [comment]
> No, you don’t need to call it again. Library will handle it. Also if buffer is low, messages sent, you will get a callback. Please see benchmark example.

Aah that is my bug then. Cheers 🙏
