### ISSUE TITLE
NodeJS 20 support

### ISSUE THREAD

**Issue by fonty1** [murat-dogan/node-datachannel#164]
Hey, recently a dev bumped into this error - I believe support needs to be added for NodeJS v20 on your side?

![image](https://github.com/murat-dogan/node-datachannel/assets/1593398/f431cc94-e78a-4c0c-b7e7-044498c8cb37)

Thanks for taking a look and warm regards from Streamr!

**Comment by murat-dogan** [comment]
Hello,
I have created a new release with Node V20 support.

https://github.com/murat-dogan/node-datachannel/releases/tag/v0.4.3

**Comment by fonty1** [comment]
Brilliant, thanks @murat-dogan
