### ISSUE TITLE
turn udp and libjuice are always used even when compiled with libnice

### ISSUE THREAD

**Issue by mghadam** [murat-dogan/node-datachannel#165]
I am trying to use node-datachannel on debian for raspberrypi with libnice to get TURN over TLS/TCP support. The command provided in the build documentation fails:

```
# npm run install -- -DUSE_NICE=1

> node-datachannel@0.4.3 install
> prebuild-install || (npm install --ignore-scripts --production=false && npm run _prebuild) "-DUSE_NICE=1"

sh: 1: Syntax error: word unexpected
npm ERR! code 2
npm ERR! path /usr/src/node-datachannel
npm ERR! command failed
npm ERR! command sh -c prebuild-install || (npm install --ignore-scripts --production=false && npm run _prebuild) "-DUSE_NICE=1"

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-07-15T12_33_03_939Z-debug.log
```

I tried to use `npm run install-nice` instead and it compiled successfully with appropriate flags:
```
[
  '/usr/bin/node',
  '/usr/src/node-datachannel/node_modules/.bin/cmake-js',
  'build',
  '--CDUSE_NICE=1'
]
info TOOL Using Unix Makefiles generator.
info CMD CONFIGURE
info RUN [
info RUN   'cmake',
info RUN   '/usr/src/node-datachannel',
info RUN   '--no-warn-unused-cli',
info RUN   '-G',
info RUN   'Unix Makefiles',
info RUN   '-DCMAKE_JS_VERSION=6.3.0',
info RUN   '-DCMAKE_BUILD_TYPE=Release',
info RUN   '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/usr/src/node-datachannel/build/Release',
info RUN   '-DCMAKE_JS_INC=/root/.cmake-js/node-arm64/v12.22.12/include/node;/usr/src/node-datachannel/node_modules/nan',
info RUN   '-DCMAKE_JS_SRC=',
info RUN   '-DNODE_RUNTIME=node',
info RUN   '-DNODE_RUNTIMEVERSION=12.22.12',
info RUN   '-DNODE_ARCH=arm64',
info RUN   '-DUSE_NICE=1'
info RUN ]
```

I then install it globally with `npm install -g .`. Even in this situation with the compiled library `node-datachannel@0.4.3 -> /usr/src/node-datachannel` , I see libjuice is used in the logs:
```
2023-07-15 17:19:04.641 DEBUG [259579] [rtc::impl::Init::doInit@110] Global initialization
2023-07-15 17:19:04.652 DEBUG [259586] [rtc::impl::Certificate::Generate@213] Generating certificate (OpenSSL)
2023-07-15 17:19:04.653 DEBUG [259587] [rtc::impl::Certificate::Generate@213] Generating certificate (OpenSSL)
2023-07-15 17:19:04.653 DEBUG [259579] [rtc::impl::IceTransport::IceTransport@49] Initializing ICE transport (libjuice)
```
and the `turns:` for turn over tls OR `?transport=tcp` for turn over udp are ignored and node-datachannel always connects to the turn server via UDP.

**Comment by murat-dogan** [comment]
Thank you for reporting this issue.
You are right the build document is outdated and wrong.

I have created a pr for this.
https://github.com/murat-dogan/node-datachannel/pull/166

After build you should be able to see this message
`2023-07-15 21:03:33.485 DEBUG [134711] [rtc::impl::IceTransport::IceTransport@377] Initializing ICE transport (libnice)`

I tried and working for me. I guess you have already installed `libnice-dev` right? Otherwise, you should get an error.

Transport over TCP is another story. You should be able to communicate with Turn server over TCP but the communication will be over UDP.

Please check this;
https://gitlab.freedesktop.org/libnice/libnice/-/issues/97

**Comment by mghadam** [comment]
Thank you, I confirm that libnice compiles and runs now.

**Comment by murat-dogan** [comment]
Actually, I didn't touch the `install-nice` script but anyway, if it is fixed then it is ok.
Thank you for feedback.

**Comment by mghadam** [comment]
> Actually, I didn't touch the `install-nice` script but anyway, if it is fixed then it is ok. Thank you for feedback.

Shall I manually copy the compiled package `build/Release/node_datachannel.node` to `/usr/local/lib/node_modules/node-datachannel/build/Release/node_datachannel.node` to use the compiled module? I noticed that `npm install -g .` always installs the version with libjuice even after compiling with libnice

**Comment by murat-dogan** [comment]
If you use `npm install -g` command, it will download and install version from net. So you need to replace it. Or maybe there could be some way to install globally the current package.
