### ISSUE TITLE
error: variable 'tot_retrans' set but not used

### ISSUE THREAD

**Issue by reececomo** [murat-dogan/node-datachannel#174]
Hello, I'm getting a similar issue to #153 on MacOS (Ventura 13.5), building [v0.4.2 via @geckos.io/server](https://github.com/geckosio/geckos.io).

```sh
[ 20%] Building C object _deps/libdatachannel-build/deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_indata.c.o
/gameserver/node_modules/node-datachannel/build/_deps/libdatachannel-src/deps/usrsctp/usrsctplib/netinet/sctp_indata.c:3323:6: error: variable 'tot_retrans' set but not used [-Werror,-Wunused-but-set-variable]
        int tot_retrans = 0;
            ^
1 error generated.
make[2]: *** [_deps/libdatachannel-build/deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_indata.c.o] Error 1
make[1]: *** [_deps/libdatachannel-build/deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/all] Error 2
```

Any tips on debugging?

**Comment by reececomo** [comment]
Looks like it's caused by:

- https://github.com/lerouxrgd/datachannel-rs/issues/35#issuecomment-1573627967
- https://github.com/sctplab/usrsctp/issues/677

**Comment by murat-dogan** [comment]
Seems like a new diagnostic flag.
Could you try to add param -Wno-unused-but-set-variable

For this specific c-lang version maybe.

**Comment by paullouisageneau** [comment]
This is a known issue on Apple Silicon with the usrsctp version currently used in libdatachannel. I'll fix it by updating usrsctp in the next release.

**Comment by reececomo** [comment]
Ah awesome, thank you for the update @paullouisageneau 🙏
