### ISSUE TITLE
CPU usage is very high when connected with about 200 peers

### ISSUE THREAD

**Issue by snowinszu** [murat-dogan/node-datachannel#175]
Hi, any suggestion to reduce cpu usage?
Version: 0.4.2

**Comment by paullouisageneau** [comment]
Are the peers idle or do you send/receive data? If so, at what approximate rate?

**Comment by snowinszu** [comment]
The peers is not idle, I send and receive data frequently,  at approximate 1Mb per second per peer.

**Comment by murat-dogan** [comment]
Hello,

I think we can close this issue.
If you have further questions please don't hesitate to re-open it.
