### ISSUE TITLE
statically include vcruntime on windows 

### ISSUE THREAD

**Issue by porsager** [murat-dogan/node-datachannel#18]
Hi.

It would be really nice to have a completely static build on windows. The only thing missing afaict is eg. `vcruntime`

Thanks.

**Comment by murat-dogan** [comment]
Sure. It is all about adding a linker option.
I will add it tomorrow.

I am not using windows normally.
Thank you for reporting.

**Comment by murat-dogan** [comment]
Resolved with v0.0.16

**Comment by murat-dogan** [comment]
Hi @porsager ,

Did you have time to test it?

**Comment by porsager** [comment]
Yeah, I'm fiddling around with it now. Works great :) 

I'm having trouble connecting outside the local network, but hopefully it's just because my stun/turn setup has issues ;)

**Comment by murat-dogan** [comment]
You can create an account for testing from https://xirsys.com/
