### ISSUE TITLE
terminate called after throwing an instance of 'Napi::Error'

### ISSUE THREAD

**Issue by snowinszu** [murat-dogan/node-datachannel#187]
I got this error, but not sure it is from node-datachannel or from the app:
terminate called after throwing an instance of 'Napi::Error'
what():  Cannot read properties of undefined (reading 'length')

**Comment by murat-dogan** [comment]
Hello.
I guess this could be related to anything.

Maybe you can start node-datachannel with more logging to see it.
And could you please share the whole error output, with stack.

For log enabling;
```
// Log Level
nodeDataChannel.initLogger("Debug");
```

**Comment by snowinszu** [comment]
This error did not happen frequently, and there is no error stack in output.
And I cannot add debug because it only happen in production.

**Comment by murat-dogan** [comment]
Any update on this?
