### ISSUE TITLE
Unable to catch exceptions

### ISSUE THREAD

**Issue by juslesan** [murat-dogan/node-datachannel#20]
Hello,

It seems that currently it is not possible to catch errors that originate from the libdatachannel library. Instead its required to check the inputs for any invalid arguments before using the libraries functions. If this is not done the entire process will crash. This was fine until a mysterious error without any stack trace or error message has made things difficult. `terminate called after throwing an instance of 'std::runtime_error'` is the only line that I have been able to find in the logs. This makes debugging the issue pretty much impossible. Reproducing is also difficult as there are quite a bit of AWS deployed machines in the experiment.

Would it be possible to add some mechanisms that allow for catching of errors in the libdatachannel library in nodejs code? For example, currently when sending a message that exceeds the maxMessageSize of a datachannel the process will crash even if the statement is surrounded by a try-catch block.

Thanks!

**Comment by murat-sx** [comment]
I should check `libdatachannel` bindings function by function and add `try,catch` blocks appropriately I guess.
Let me check.

**Comment by murat-dogan** [comment]
I should check libdatachannel bindings function by function and add try,catch blocks appropriately I guess.
Let me check.

**Comment by eonicum** [comment]
I have a similar issue. The whole process crashes if something is going wrong during connection.

**Comment by murat-dogan** [comment]
Thanks for reporting.

Could you please try v0.0.17?

In this version, all native calls surrounded with `try-catch` blocks. If something goes wrong it will throw nodejs exception. 
If you need, I can also add callbacks to certain functions, so it can return error message instead of throwing error.
Please let me know.

**Comment by juslesan** [comment]
It seems that it's possible to catch errors properly now. The error messages seem to be good so far. I'll have to add some try catch blocks to my code before I can be sure that the mysterious error is gone now as I did still see it and it brought down the process.

**Comment by eonicum** [comment]
@murat-dogan, thank you! It works correctly now

**Comment by juslesan** [comment]
Hello!

The connections have been much more stable now especially during signalling. However, there is still one error that keeps crashing the nodes and I was finally able to extract the stack trace! This error might be a bit difficult to reproduce but it seems to happen when there are lots of connections or peers present.

`FATAL ERROR:  Not connected to ap-south-1-13.127.235.182-19063.
Dec 10 10:03:55 ip-10-0-3-169 bash[19308]:  1: 0xa03530 node::Abort() [node]
Dec 10 10:03:55 ip-10-0-3-169 bash[19308]:  2: 0x94e471 node::FatalError(char const*, char const*) [node]
Dec 10 10:03:55 ip-10-0-3-169 bash[19308]:  3: 0x94e47a  [node]
Dec 10 10:03:55 ip-10-0-3-169 bash[19308]:  4: 0x9d56ab napi_fatal_error [node]
Dec 10 10:03:55 ip-10-0-3-169 bash[19308]:  5: 0x7f032badcf10 Napi::CallbackScope::~CallbackScope() [/srv/broker/metrics/node_modules/node-datachannel/build/Release/node_datachannel.node]
Dec 10 10:03:55 ip-10-0-3-169 bash[19308]:  6: 0x7f032bae68dc ThreadSafeCallback::Impl::static_async_callback(uv_async_s*) [/srv/broker/metrics/node_modules/node-datachannel/build/Release/node_datachanne>
Dec 10 10:03:55 ip-10-0-3-169 bash[19308]:  7: 0x1379a66  [node]
Dec 10 10:03:55 ip-10-0-3-169 bash[19308]:  8: 0x138c545  [node]
Dec 10 10:03:55 ip-10-0-3-169 bash[19308]:  9: 0x137a398 uv_run [node]
Dec 10 10:03:55 ip-10-0-3-169 bash[19308]: 10: 0xa438d4 node::NodeMainInstance::Run() [node]
Dec 10 10:03:55 ip-10-0-3-169 bash[19308]: 11: 0x9d1735 node::Start(int, char**) [node]
Dec 10 10:03:55 ip-10-0-3-169 bash[19308]: 12: 0x7f03414110b3 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
Dec 10 10:03:55 ip-10-0-3-169 bash[19308]: 13: 0x96971c  [node]
`

What is clear is that the error occurs when the message is being sent. The puzzling thing is when this error happens the library reports that the faulty connection's state is 'connected'. The error always crashes the process even with if checks and try catch blocks.

**Comment by murat-dogan** [comment]
This error occurs on the peer that sends or the peer that receives the message. 
Do you know it?

Error occurs while calling a callback.

`FATAL ERROR: Not connected to ap-south-1-13.127.235.182-19063.`
Where did this message come from?

**Comment by juslesan** [comment]
I found a piece of code on end that throws the error 'Not connected to {peerId}' but I'm not sure where the FATAL ERROR comes from. I'll see if removing the throw helps at all.

**Comment by juslesan** [comment]
It seems that this part of this issue was on my end! 

On another note, do you have plans to implement failed states for the connections at some point? It could help with setting up retry logic etc.

Thanks for the help and the update to the error handling!

**Comment by murat-dogan** [comment]
```
peer2.onStateChange((state) => {
    console.log("Peer2 State:", state);
});
```

This cb should give the all state changes including failing, disconnect messages.

What is the situation on your side?

**Comment by juslesan** [comment]
Currently I'm only catching 'connected', 'connecting', 'closed' states but perhaps I never hit failed states then.
