### ISSUE TITLE
how to send binary data

### ISSUE THREAD

**Issue by DZLiao** [murat-dogan/node-datachannel#21]
I want to send binary data like protocol buffer or file but the interface named sendMessage and onMessage callback only supports STRING type data, so how can I do it. Thanks.

**Comment by murat-dogan** [comment]
Hi,

I added binary data support on v0.0.18.
Pleas use `sendMessageBinary(Buffer)` function.

Could you please try and confirm it?

**Comment by porsager** [comment]
Oh man, that's great! I actually thought it was a thing missing from libdatachannel itself. I'll definitely give it a whirl sometime next week to replace my base64 solution ;)

**Comment by murat-dogan** [comment]
I am sorry for that @porsager  :)
It was just a to-do in my list.

**Comment by DZLiao** [comment]
Thank you for your help so fast and it's great. I have already tested it with a protocol buffer message and success. 👍👍

**Comment by porsager** [comment]
Also replaced my base64 thing now. Works great ❤️
