### ISSUE TITLE
scaling data channels

### ISSUE THREAD

**Issue by RichardWright** [murat-dogan/node-datachannel#214]
Hi!

Cool lib, I was wondering if anyone on here had used this lib at scale? eg for broadcasting to 1000+ connections, ideally with high frequency data. It seems to be a good replacement for a simplex websocket, but can't find much usage of it for these things.

Thanks!

**Comment by murat-dogan** [comment]
Hello,
Yes, streamr is using as base comm library.
https://streamr.network/

**Comment by murat-dogan** [comment]
If you dont mind. I am closing the issue.
