### ISSUE TITLE
Problems compiling in Docker Alpine Linux.

### ISSUE THREAD

**Issue by sleep9** [murat-dogan/node-datachannel#219]
```
npm ERR! CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
npm ERR!   Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
npm ERR!   system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY) (found
npm ERR!   version "3.0.12")
```

dockerfile

```
FROM node:18.16.0-alpine3.17
ENV OPENSSL_ROOT_DIR=/usr/bin/openssl
RUN apk update && apk add \
  openssl \
  openssl-dev \
  make \
  g++ \
  cmake 
RUN mkdir -p /opt/app/relay-rtc
COPY package.json package-lock.json ./opt/app/relay-rtc/
COPY ./ ./opt/app/relay-rtc
WORKDIR /opt/app/relay-rtc
RUN npm install
EXPOSE ${MY_PORT}
CMD [ "npm", "start"]
```

**Comment by murat-dogan** [comment]
Please check 
https://github.com/murat-dogan/node-datachannel/tree/master/examples/build

> ENV OPENSSL_ROOT_DIR=/usr/bin/openssl

For me this doe not seem correct. You can try not to set it at all.

**Comment by sleep9** [comment]
Switching to ubuntu container works, was not interested in chasing down the problem. For anyone in the future try the following:

`FROM node:18.16.0
RUN apt update 
RUN apt install -y \
  openssl \
  libssl-dev \
  make \
  g++ \
  cmake 
RUN mkdir -p /opt/app/relay-rtc
COPY package.json package-lock.json ./opt/app/relay-rtc/
COPY ./ ./opt/app/relay-rtc
WORKDIR /opt/app/relay-rtc
RUN npm install
EXPOSE $(YOUR_PORT)
CMD [ "npm", "start"]`
