### ISSUE TITLE
Adding options to createDataChannel to allow the possibility of unordered, unreliable datachannels?

### ISSUE THREAD

**Issue by RaggarDK** [murat-dogan/node-datachannel#23]
createDataChannel doesn't take into account the possibility of options such as maxretransmits and ordered when creating the datachannel, however libdatachannel does, so I assume this could be fixed relatively easy?
https://github.com/murat-dogan/node-datachannel/blob/d517038ced39a542e70f0e610337b94cbaf49101/src/peer-connection-wrapper.cpp#L270
https://github.com/paullouisageneau/libdatachannel/blob/31c154e9d9674671c28beaec247d1579d588296f/src/peerconnection.cpp#L339

**Comment by murat-dogan** [comment]
Hi,

I added these options;
```
export enum ReliabilityType {
    Reliable = 0, Rexmit = 1, Timed = 2
}

export interface DataChannelInitConfig {
    reliability: {
        type: ReliabilityType;
        unordered: boolean;
        rexmit: number;
    }
    negotiated: boolean;
    protocol: string;
}
```

You can use these options while creating data channel like;
```
dc1 = peer1.createDataChannel("test",{reliability:{unordered:true}});
``` 

Please check v0.0.19 & confirm it is working on your side.

**Comment by RaggarDK** [comment]
Tested locally and works perfectly. Thank you.
Closing issue.
