### ISSUE TITLE
Expose WebSocket functionality of libdatachannel?

### ISSUE THREAD

**Issue by ptesavol** [murat-dogan/node-datachannel#233]
Hi

Would it be possible to also expose the WebSocket functionality of libdatachannel in node-datachannel? There are the well-known websocket packages for nodejs (ws, websocket, and uWebSockets), but they all have their own shortcomings when it comes to heavy-duty use cases with hundreds of connections per node.

**Comment by ptesavol** [comment]
I just created a pull request that brings the WebSocket functionality of libdatachannel into node-datachannel: https://github.com/murat-dogan/node-datachannel/pull/235. This might require a little refactoring and more testing, but let me know what you think.

**Comment by murat-dogan** [comment]
I'm sorry for not getting back to you sooner.
This is a good idea.

For me PR is ok. Just small notes.

**Comment by ptesavol** [comment]
There is a lot of copy-paste code, but using inheritance seems to be a complex topic when using Node-API, so I didn't go there yet: https://mmomtchev.medium.com/c-class-inheritance-with-node-api-and-node-addon-api-c180334d9902

**Comment by murat-dogan** [comment]
Hello @ptesavol
For me it is ok.
Just please solve the typo

**Comment by ptesavol** [comment]
Hi @murat-dogan 
Sorry, which typo do you mean? For some reason I cannot see your notes in the PR discussion

**Comment by murat-dogan** [comment]
Please check conversation tab.
There is a typo and conflicts.

**Comment by ptesavol** [comment]
Unfortunately on my machine I cannot see anything in the conversation tab of https://github.com/murat-dogan/node-datachannel/pull/235. Could you do the small fixes before merging, that might be the easiest way to go?

**Comment by murat-dogan** [comment]
I merge the PR.
Thanks.
