### ISSUE TITLE
OpenSSL 1.1

### ISSUE THREAD

**Issue by kevglass** [murat-dogan/node-datachannel#241]
I'm trying to get the library running in a linux container, however it looks like the build is linked against OpenSSL 1.1.1 - and I can't get a supported package for the shared libraries for libssl.so.1.1 - earliest I can get in 3.

I'm going to try install 1.1 manually but wanted to check this is whats expected?

**Comment by kevglass** [comment]
Hmm, or in 0.6.0 its statically linked?

**Comment by murat-dogan** [comment]
Yes exactly.
Could you please try 0.6.0?

**Comment by kevglass** [comment]
Yep, I built 0.6.0 to test the CJS module - and all worked well.

Thank you for all your hard work.
