### ISSUE TITLE
Add index.d.cts file to improve CommonJS support

### ISSUE THREAD

**Issue by ptesavol** [murat-dogan/node-datachannel#242]
Currently using node-datachannel in a CommonJS typescript projects requires using very specific tsconfig settings in the importing project, namely:
 
```json 
 "compilerOptions": {
         "module": "CommonJS",
        "moduleResolution": "Node10"
    },
 ``` 

To make the import work with other "module" and "moduleResolution" settings, a index.d.cts file would be required in "lib/" This file can be a copy of the current index.d.ts file, and maybe it could be created in the "prepublishOnly" script.

The reason why a separate index.d.cts file is required seems to be related to this open issue in typescript: https://github.com/microsoft/TypeScript/issues/52363

**Comment by murat-dogan** [comment]
Could you please confirm this PR solves the issue?
https://github.com/murat-dogan/node-datachannel/pull/244

**Comment by ptesavol** [comment]
Thank you for the swift reply, the PR solves the issue.

**Comment by ptesavol** [comment]
Hi, could you publish v 0.8.0 to NPM so we can take it into use?

**Comment by murat-dogan** [comment]
Version released
