### ISSUE TITLE
Update libdatachannel for v0.21.1

### ISSUE THREAD

**Issue by asimovc** [murat-dogan/node-datachannel#262]
I'm having errors in build node-datachannel and the problem is about version since is [fixed](https://github.com/paullouisageneau/libdatachannel/issues/1213#issuecomment-2172752538) in libdatachannel upstream. Here lhe [logs](https://0x0.st/XcF6.log)

**Comment by murat-dogan** [comment]
Hi,
There are some open PRs.
I hope we can create a new release till weekend.

**Comment by murat-dogan** [comment]
v0.9.2 released

**Comment by asimovc** [comment]
I still having the same issue when i install it in npm @murat-dogan

**Comment by murat-dogan** [comment]
Hello @asimovc 

I can see that commit in src 
https://github.com/paullouisageneau/libdatachannel/pull/1183

**Comment by murat-dogan** [comment]
I have just released v0.10.0
https://github.com/murat-dogan/node-datachannel/releases/tag/v0.10.0

V0.10.0 also supports `musl` binaries.
Could you please try and report here?

**Comment by asimovc** [comment]
Builds fine, thank you
