### ISSUE TITLE
TURN credentials invalid with format of `username:hash:password`

### ISSUE THREAD

**Issue by lukepolo** [murat-dogan/node-datachannel#27]
Related https://github.com/paullouisageneau/libdatachannel/issues/340

I am using coturn , and the format is

```
{
   username: "1613774196:someUser@gmail.com",
   credential: "XChjpcy9z9vf0NPKnqJbs8KTR+4=" // base 64 hash
}
```

**Comment by murat-dogan** [comment]
Thank you for reporting.

Could you please try with v0.0.22 ?
https://github.com/murat-dogan/node-datachannel/releases/tag/v0.0.22

**Comment by lukepolo** [comment]
Thanks !! Ill try it today!

**Comment by lukepolo** [comment]
Ran into a slight issue, 

The ice Server contract is missing the `Type`

https://github.com/paullouisageneau/libdatachannel/blob/b5589dbd57141932c523e3e26f34da2d0fb47803/include/rtc/configuration.hpp

Still testing to see if its actually required

**Comment by murat-dogan** [comment]
Actually we don't need it.

 If you create config with only hostname & port than it is a STUN server, if you provide username,password,relayType than it is a TURN server.

**Comment by lukepolo** [comment]
Yup it seems to work, just need to make `relayType` optional in your interface, and its good togo ! 

`2021-02-25 14:03:41.206 INFO  [1837] [rtc::IceTransport::LogCallback@341] juice: agent.c:1475: TURN allocation successful`

**Comment by murat-dogan** [comment]
Yes, I forgot to add `?`. 
I just added & pushed it.

**Comment by lukepolo** [comment]
Awsome, thank you for your support / and great package!
