### ISSUE TITLE
Websocket Server cannot send ArrayBuffer or TypedArray to client

### ISSUE THREAD

**Issue by Msfrhdsa** [murat-dogan/node-datachannel#274]
So I guess this is expected behavior, right? Can node-datachannel websocket only transfer strings? Any plans to change this?
```
[WebSocketWrapper::sendMessage@350] sendMessage() called
```

**Comment by paullouisageneau** [comment]
You can send buffers with `WebSocket.sendMessageBinary()`.

**Comment by Msfrhdsa** [comment]
Oh, I don’t even understand how I missed this. Yes, everything is fine, it works great.
