### ISSUE TITLE
How to build the node_datachannel.node binary???

### ISSUE THREAD

**Issue by M-Stenzel** [murat-dogan/node-datachannel#277]
Hi team, I use the peertube software, which makes use of node-datachannel software.

Unfortunately I run an older distro (SuSE) which still uses version 2.22 of the glibc library.
Because of that your binary fails to run, and latest version of peertube (6.2.0) fails to run.

How can I build the binary **node_datachannel.node** ? I could not find this information in the documentation.
"npm i" does not build this binary.

Thanks in advance, Martin.

**Comment by murat-dogan** [comment]
Hi Martin,
If it finds a suitable binary, it downloads and not builds.
But I am afraid it does not check glibc version.
If you need to build it you need to run “npm run build” command.

**Comment by M-Stenzel** [comment]
That was quick! 

Well did some further "research" myself...

I tried

"npm i --build-from-source" which seems to be correct, but it fails with

```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY) (found
  version "3.0.8")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindOpenSSL.cmake:670 (find_package_handle_standard_args)
  CMakeLists.txt:24 (find_package)


-- Configuring incomplete, errors occurred!
ERR! OMG Process terminated: 1
prebuild ERR! build Error: Failed to build cmake with exit code 1
prebuild ERR! build     at ChildProcess.<anonymous> (/tmp/node/node-datachannel-0.11.0/node_modules/prebuild/cmakebuild.js:32:19)
prebuild ERR! build     at ChildProcess.emit (node:events:517:28)
prebuild ERR! build     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
npm error code 2
npm error path /tmp/node/node-datachannel-0.11.0
npm error command failed
npm error command sh -c prebuild-install -r napi || (npm install --ignore-scripts --production=false && npm run _prebuild)
```

Weird, since I tried with both version 1.1 and 3.0 of the openssl library.

"npm run build" gives me

```
> node-datachannel@0.11.0 build
> cmake-js build

[
  '/usr/bin/node18',
  '/tmp/node/node-datachannel-0.11.0/node_modules/.bin/cmake-js',
  'build'
]
info TOOL Using Ninja generator, because ninja is available.
info CMD BUILD
info RUN [
info RUN   'cmake',
info RUN   '--build',
info RUN   '/tmp/node/node-datachannel-0.11.0/build',
info RUN   '--config',
info RUN   'Release'
info RUN ]
ninja: error: loading 'build.ninja': No such file or directory
ERR! OMG Process terminated: 1
```

**Comment by murat-dogan** [comment]
Please be sure that you have openssl-dev installed
If yes try to set OPENSSL_ROOT_DIR manually

openssl V1 or V3 is ok

**Comment by M-Stenzel** [comment]
Thanks again. Actually this is an rpm based Linux distro.
Anyway, I installed version 1.1.1 from sources, and npm found this installation (by defining OPENSSL_ROOT_DIR), and the compilation of the program worked as expected!
Thank you again! I will tell the developers of peertube about this dependency,

Martin.

**Comment by murat-dogan** [comment]
Normally you don’t need to set it manually. Cmake should find it automatically.
But anyway good that you have it figured out 

Thanks for writing here
