### ISSUE TITLE
Missing Arm64 Mac (M1 apple silicon) prebuilt

### ISSUE THREAD

**Issue by ouya99** [murat-dogan/node-datachannel#28]
I did the build on arm64 and could upload "node-datachannel-v0.0.22-node-v88-darwin-arm64.tar.gz" 
Would you integrate it please? It would solve a dependancy issue for me . Thank you

**Comment by murat-dogan** [comment]
Hi,

I don't have any experience on Mac.
Could you please guide me or create a pull request?

I am using github actions to build prebuilt binaries. You can check it here;
https://github.com/murat-dogan/node-datachannel/blob/master/.github/workflows/build.yml

I already added node v15 to build list.

**Comment by ouya99** [comment]
here you go : https://github.com/murat-dogan/node-datachannel/pull/29

do not know where you store your prebuilds, i put it in a folder /prebuilds

**Comment by porsager** [comment]
I think this is better solved with a fork and different npm package provided by @ouya99 until github actions can support M1.

It's not possible for anyone to inspect the uploaded binary if done this way.

**Comment by murat-dogan** [comment]
We have to find a way to create prebuilt binaries with github actions.
I don't create these binaries locally, and also git project does not have these binaries as files.

If we don't have a way to do like that, then @porsager is right.

**Comment by ouya99** [comment]
@murat-dogan how do you create your prebuilds?

**Comment by porsager** [comment]
Github Actions don't support M1 yet, and it doesn't seem like it's anything that's [happening soon](https://github.com/actions/virtual-environments/issues/2187).

It might be [sooner using self hosted runners](https://github.com/actions/runner/issues/805), but that'd require someone sponsoring that.

**Comment by murat-dogan** [comment]
I am creating prebuilds with github actions.

https://github.com/features/actions  
https://github.com/murat-dogan/node-datachannel/blob/master/.github/workflows/build.yml

**Comment by ouya99** [comment]
by setting 
OPENSSL_ROOT_DIR: /usr/local/opt/openssl
OPENSSL_LIBRARIES: /usr/local/opt/openssl/lib

I managed to build it automatically on my mac. Sorry did miss that you actually do not provide any prebuild and its built locally which works fine.
