### ISSUE TITLE
Does not work with other ice servers

### ISSUE THREAD

**Issue by 0wwafa** [murat-dogan/node-datachannel#285]
this won't work (but works in the browser)
`{ iceServers: ['stun:142.250.82.249:3478'] }   << that's a google turn server.
`
Also:
no idea how to pass credentials.

**Comment by Aviv1000** [comment]
its need to be like this:
```
iceServers: [
{
urls: ["stun:142.250.82.249:3478"]
},
{
urls: ["stun:142.250.82.249:3478"]
username: "test",
credential: "test"
}
]
```

**Comment by murat-dogan** [comment]
Hello,
This format will work for bindings but will not work for polyfills.
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/RTCPeerConnection#iceservers

It should be like @Aviv1000 mentioned.

**Comment by paullouisageneau** [comment]
FYI, for bindings, username and passwords must be specified in the URI with the format `turn:username:password@hostname:port`.

**Comment by murat-dogan** [comment]
I am closing the issue. If you have further questions, please feel free to re-open it.
