### ISSUE TITLE
Sponsorship

### ISSUE THREAD

**Issue by fonty1** [murat-dogan/node-datachannel#30]
Hey Murat,

Matthew from Streamr here - we're big fans of your library and we'd like to offer some sponsorship funds for you to support good quality open source libraries!

This is the first time I've done this, but as I see it, we have two options to support you: 
1. Through the GitHub Sponsorship program (you need to activate it on your account) [Github Sponsors](https://docs.github.com/en/github/supporting-the-open-source-community-with-github-sponsors/setting-up-github-sponsors-for-your-user-account)
2. Send me an email at matthew.fontana@streamr.network and I'll send you some funds directly. 

Best, 
Matthew

**Comment by murat-dogan** [comment]
Thank you very much for your kind words. I want to say two things;

* I also don't know this funding procedures, but "GitHub sponsors" could be better. So you will be listed as sponsor.
* As you know I am using `libdatachannel` as the base library. If it is convenient for you, I ask you to divide the amount in half and pay half to me and the other half to @paullouisageneau. I think it will be more ethical.

Thank you again!

**Comment by fonty1** [comment]
Sounds good :) That sounds fair of course! Will do. 

Thanks for you email, let me know when your sponsorship is setup and we'll take it from there.

**Comment by paullouisageneau** [comment]
> As you know I am using `libdatachannel` as the base library. If it is convenient for you, I ask you to divide the amount in half and pay half to me and the other half to @paullouisageneau. I think it will be more ethical.

Thank you @murat-dogan, much appreciated!

**Comment by fonty1** [comment]
> > As you know I am using `libdatachannel` as the base library. If it is convenient for you, I ask you to divide the amount in half and pay half to me and the other half to @paullouisageneau. I think it will be more ethical.
> 
> Thank you @murat-dogan, much appreciated!

I sent you an email @paullouisageneau - I would be super grateful if you could take a look :)

**Comment by hpihkala** [comment]
Both gentlemen sponsored now! 😊  Keep up the great work!

**Comment by paullouisageneau** [comment]
@hpihkala Thank you so much!

**Comment by pimterry** [comment]
@paullouisageneau @murat-dogan I'd also like to set up a small monthly sponsorship to both of you for your work on libdatachannel & node-datachannel to say thanks for all your hard work.

It looks like your GitHub sponsors isn't active now though @murat-dogan, and I can see there's also https://opencollective.com/node-datachannel but there's no options there to donate (and no FUNDING.yml in this repo listing alternatives).

Let me know what the best way to do this is. Personally, selfishly, I'd find it really convenient if that [node-datachannel org](https://opencollective.com/node-datachannel) on OpenCollective accepted donations, and then that could redistribute them between the two of you (and any other appropriate contributors) in whatever way you see fit. I already donate to quite a few other projects via OpenCollective, and having a single payment & invoice for all my sponsorships is helpful. Alternatives are good too of course, whatever's best for you, that's just the option that would be best from my POV.

**Comment by murat-dogan** [comment]
Hi @pimterry ,

Thank you very much for your kind thoughts.
github sponsorship is working only with stripe which is not available in my country (Istanbul,Turkey) yet.

Opencollective is an alternative and could be better. 
I will try to set it up & I will try to discuss with @paullouisageneau .

**Comment by murat-dogan** [comment]
Hi again,

I have just finished the setting up open-collective account.
Now project has a sponsor link on main page.

Thanks,

**Comment by paullouisageneau** [comment]
@pimterry Great, thank you very much!

@murat-dogan Thanks for the invitation, I joined the open collective!
