### ISSUE TITLE
Types aren't exported

### ISSUE THREAD

**Issue by pimterry** [murat-dogan/node-datachannel#300]
Hi @murat-dogan! Sorry I didn't get time to test after the ping on #293, I've been off work for a little while. Back on it now, and I've just updated.

The runtime behaviour all seems to work as expected (great work!) but the one issue I have run into is that various types that were previously defined aren't exported.

There's probably more examples, but in my case specifically I was previously importing `Direction` and `DescriptionType` and both are no longer directly available. Is it possible to add those back?

**Comment by murat-dogan** [comment]
Thanks for reportıng.

Could you please try with master?
I have exported also types here.
https://github.com/murat-dogan/node-datachannel/blob/05b362c3c4e6924d192877208b84fe4d49ebfa7a/src/lib/index.ts#L175

**Comment by murat-dogan** [comment]
I have also released a new version :)
https://github.com/murat-dogan/node-datachannel/releases/tag/v0.21.0

**Comment by pimterry** [comment]
Works great, thanks for the quick fix @murat-dogan!
