### ISSUE TITLE
Error with Polyfill RTCPeerConnection.getStats

### ISSUE THREAD

**Issue by Aviv1000** [murat-dogan/node-datachannel#301]
this code:
`pc.getStats(null).then(function(stats) { ...`
give me some error:
TypeError: Cannot read properties of null (reading 'local')
node-datachannel\dist\cjs\polyfill\RTCPeerConnection.cjs
its should be like this with promise getStats(null).then(function(stats) { same as what work for the browser.
can fix that error?

**Comment by murat-dogan** [comment]
I can not reproduce it.
Could you please share more details?

**Comment by Aviv1000** [comment]
try call the function before you enstablish the connection between two peers

**Comment by murat-dogan** [comment]
Ok. I can reproduce the issue. However, this is not related to calling the function with null.
I pushed a fix.
Thanks for reporting.

**Comment by murat-dogan** [comment]
I am closing the issue.
If you have further questions, please feel free to reopen it.
