### ISSUE TITLE
Error "Cannot read property 'push' of undefined" when calling createDataChannel

### ISSUE THREAD

**Issue by visgotti** [murat-dogan/node-datachannel#31]
Hey, when I try to create a data channel, I'm getting the error "Cannot read property 'push' of undefined" Not sure how to debug this, but wondering if there's a known solution or I'm doing something funky?

here's my code -

```
const peerConnection = new nodeDataChannel.PeerConnection('uid', { 
     iceServers: [
                'stun:stun1.l.google.com:19302',
                'stun:stun2.l.google.com:19302',
                'stun:stun3.l.google.com:19302',
                'stun:stun4.l.google.com:19302'
            ],
            portRangeBegin: 7400,
            portRangeEnd: 7500
})

const dataChannel = peerConnection.createDataChannel('string_id', {
    negotiated: false,
    protocol: "UDP",
    reliability: {rexmit: 0, type: 2, unordered: true},
})
```

the full error is - 

FATAL ERROR:  Cannot read property 'push' of undefined
 1: 00007FF71E325EBF napi_wrap+114095
 2: 00007FF71E2D0B46 v8::base::CPU::has_sse+66998
 3: 00007FF71E2D1946 v8::base::CPU::has_sse+70582
 4: 00007FF71E2D1129 v8::base::CPU::has_sse+68505
 5: 00007FF71E2F6640 napi_fatal_error+160
 6: 00007FFAE7680676 rtc::WebSocket::`default constructor closure'+198
 7: 00007FFAE78F40E6 juice_crc32+350646
 8: 00007FFAE78C7650 juice_crc32+167712
 9: 00007FFAE78C65C1 juice_crc32+163473
10: 00007FFB52081336 RtlCaptureContext+1382
11: 00007FFAE768C63C rtc::Channel::availableAmount+12716
12: 00007FF71E37677B uv_async_send+331
13: 00007FF71E375F1C uv_loop_init+1212
14: 00007FF71E3760E4 uv_run+244
15: 00007FF71E286F61 v8::internal::Scope::locals+31841
16: 00007FF71E2FA593 node::Start+275
17: 00007FF71E166A9C RC4_options+340380
18: 00007FF71EFF34A8 v8::internal::SetupIsolateDelegate::SetupHeap+1300536
19: 00007FFB500C7C24 BaseThreadInitThunk+20
20: 00007FFB5204D721 RtlUserThreadStart+33
npm ERR! code ELIFECYCLE
npm ERR! errno 134

**Comment by visgotti** [comment]
Okay so it seems like it only happens when I use the callbacks 

   ```
     peerConnection.onLocalDescription( (sdp, type) => {
        });
        peerConnection.onLocalCandidate((candidate: string, mid: string) => {
        });
```

Now the error is looking like - 

FATAL ERROR:  Cannot read property 'forEach' of undefined
 1: 00007FF71E325EBF napi_wrap+114095
 2: 00007FF71E2D0B46 v8::base::CPU::has_sse+66998
 3: 00007FF71E2D1946 v8::base::CPU::has_sse+70582
 4: 00007FF71E2D1129 v8::base::CPU::has_sse+68505
 5: 00007FF71E2F6640 napi_fatal_error+160
 6: 00007FFAE7680676 rtc::WebSocket::`default constructor closure'+198
 7: 00007FFAE78F40E6 juice_crc32+350646
 8: 00007FFAE78C7650 juice_crc32+167712
 9: 00007FFAE78C65C1 juice_crc32+163473
10: 00007FFB52081336 RtlCaptureContext+1382
11: 00007FFAE768C63C rtc::Channel::availableAmount+12716
12: 00007FF71E37677B uv_async_send+331
13: 00007FF71E375F1C uv_loop_init+1212
14: 00007FF71E3760E4 uv_run+244
15: 00007FF71E286F61 v8::internal::Scope::locals+31841
16: 00007FF71E2FA593 node::Start+275
17: 00007FF71E166A9C RC4_options+340380
18: 00007FF71EFF34A8 v8::internal::SetupIsolateDelegate::SetupHeap+1300536
19: 00007FFB500C7C24 BaseThreadInitThunk+20
20: 00007FFB5204D721 RtlUserThreadStart+33

**Comment by visgotti** [comment]
Okay this was a non issue... the stack trace lead me to believe there was something wrong in the low level.. but it was just an uninitialized array inside my class.. not sure why the error looked like that though.

**Comment by murat-dogan** [comment]
I am glad that you figured it out.
If you have any other question please re-open it.
