### ISSUE TITLE
Multiplexing and custom ssrc don't work

### ISSUE THREAD

**Issue by NysoS** [murat-dogan/node-datachannel#317]
For a video stream with 'new Video(...)', when an SSRC is added with 'addSSRC', the client receives the custom SSRC but also a second auto-generated SSRC. Only the second auto-generated SSRC receives the RTP packets.

For multiplexing, the client correctly receives both distinct streams with their SSRC, but neither of them receives the RTP packets.

For a single stream with chrome://webrtc-internals/
![image](https://github.com/user-attachments/assets/579ecf9f-c005-4380-8136-1679d186e038)

For a multi stream with flux avec chrome://webrtc-internals/
![image](https://github.com/user-attachments/assets/483cc6ed-7f05-4dc8-8023-07b3bad9dd65)

On the client (web browser), the codec used is undifed : "Flux vidéo avec SSRC : 42
camera:172 Paquets reçus : 0
camera:173 Codec utilisé : undefined",

Server side: 
![image](https://github.com/user-attachments/assets/0cd2b2ca-2cbb-411a-a97e-5e9673800562)

**Comment by NysoS** [comment]
I found my problem, I use ffmpeg to get the rtps stream and send in rtp, and I just forgot to assign an ssrc on my rtp packages

**Comment by murat-dogan** [comment]
Thank you for the info
