### ISSUE TITLE
Max message size configurability

### ISSUE THREAD

**Issue by juslesan** [murat-dogan/node-datachannel#33]
Hi @murat-dogan !

Would it possible to update this library to use the v0.12.1 of lib-datachannel quite soon? The new version includes configurability for the maxMessageSizes for datachannels which I will need in the recent future.

Thanks!

**Comment by murat-dogan** [comment]
It is updated. Please check v0.1.1. 
`maxMessageSize` is now an option like that;
```
export interface RtcConfig {
    iceServers: (string | IceServer)[];
    proxyServer?: ProxyServer;
    enableIceTcp?: boolean;
    portRangeBegin?: Number;
    portRangeEnd?: Number;
    maxMessageSize?: Number;
}
```

npm package is released also.

**Comment by juslesan** [comment]
It seems to work as expected

Thanks a lot!
