### ISSUE TITLE
Unexpected high memory consumption for datachannel

### ISSUE THREAD

**Issue by boa86** [murat-dogan/node-datachannel#43]
Hi there!
I'd like to use this library and played a little bit before start. I'm making a backend to serve many datachannel connections

I found that it uses a lot of memory per peer connection with datachannel enabled (btw not sure what is reason).
For 400 datachannel connections it uses 2.6GB.
I did the same test in the latest Chrome and it does not consume so much.
Additionally, it got stuck on closing. Console.log in setTimeout print "Closed #" for several first numbers only.
I'd appreciate if you let me know if I missed something important in the code.

Please use next code to verify this:

```
const nodeDataChannel = require('node-datachannel')

// Log Level
// nodeDataChannel.initLogger("Debug")

function createConnection(id) {
  let dc1 = null
  let dc2 = null
  let peer1 = null
  let peer2 = null

  const peerOnelabel = `Peer.${id}.1`
  const peerSecondlabel = `Peer.${id}.2`

  peer1 = new nodeDataChannel.PeerConnection(peerOnelabel, { iceServers: ["stun:stun.l.google.com:19302"] })

  // Set Callbacks
  peer1.onStateChange(function (state) {
    console.log(peerOnelabel, "State:", state)
  })
  peer1.onGatheringStateChange(function (state) {
    console.log(peerOnelabel, "GatheringState:", state)
  })
  peer1.onLocalDescription(function (sdp, type) {
    // console.log(peerOnelabel, "SDP:", sdp, "Type:", type)
    peer2.setRemoteDescription(sdp, type)
  })
  peer1.onLocalCandidate(function (candidate, mid) {
    // console.log(peerOnelabel, "Candidate:", candidate)
    peer2.addRemoteCandidate(candidate, mid)
  })

  peer2 = new nodeDataChannel.PeerConnection(peerSecondlabel, { iceServers: ["stun:stun.l.google.com:19302"] })

  // Set Callbacks
  peer2.onStateChange(function (state) {
    console.log(peerSecondlabel, "State:", state)
  })
  peer2.onGatheringStateChange(function (state) {
    console.log(peerSecondlabel, "GatheringState:", state)
  })
  peer2.onLocalDescription(function (sdp, type) {
    // console.log(peerSecondlabel, "SDP:", sdp, "Type:", type)
    peer1.setRemoteDescription(sdp, type)
  })
  peer2.onLocalCandidate(function (candidate, mid) {
    // console.log(peerSecondlabel, "Candidate:", candidate)
    peer1.addRemoteCandidate(candidate, mid)
  })
  peer2.onDataChannel(function (dc) {
    console.log(peerSecondlabel, "Got DataChannel:", dc.getLabel())
    dc2 = dc
    dc2.onMessage(function (msg) {
      // console.log(peerSecondlabel, 'Received Msg:', msg)
    })
    dc2.sendMessage("Hello From" + peerSecondlabel)
  })

  dc1 = peer1.createDataChannel("test")
  dc1.onOpen(() => {
    dc1.sendMessage("Hello from" + peerOnelabel)
  })
  dc1.onMessage((msg) => {
    // console.log(peerOnelabel, 'Received Msg:', msg)
  })

  setTimeout(() => {
    console.log('Closed:', id)
    dc1.close()
    dc2.close()
    peer1.close()
    peer2.close()
    dc1 = null
    dc2 = null
    peer1 = null
    peer2 = null
    nodeDataChannel.cleanup()
  }, 5 * 1000)
}


function main() {
  for(let i = 0; i < 200; i++) {
    createConnection(i)
  }
}

main()
```

**Comment by murat-dogan** [comment]
Hi,
Thanks for reporting. Memory consumption seems too high.
Let me investigate.

**Comment by murat-dogan** [comment]
Hi again,

I made some tests. Here is my findings;

* Memory consumption is related to peer connections count not data channels count.
* With 200 open data channels within a single peer connection consumes only 20MB memory.
* 200 peer connections consume 1200MB memory
* I made a "dirty" test on libdatachannel (base lib);
  * For 200 peer connections it consumes ~2500MB

For me, it seems like it is related to base library. 
Probably it is expected, but you still can open a issue.
https://github.com/paullouisageneau/libdatachannel

**Comment by boa86** [comment]
Thanks you very much for fast answering and confirming the same memory usage I got. My task is to serve a lot of peers (avg ~1k) by nodejs. 
I'll create a discussion in the base lib repo and write link here.

**Comment by paullouisageneau** [comment]
The library is expected to consume a couple MB for each PeerConnection endpoint. This is a limitation of the SCTP implementation [usrsctp](https://github.com/sctplab/usrsctp) which allocates flat buffers instead of using a memory-efficient scheme, therefore, there is a trade-of between memory usage and max throughput (the throughput is limited by the buffer size for a given RTT). For performance reasons, libdatachannel uses 1 MB buffers by default for SCTP, which results in each PeerConnection needing 4 MB.

If you need hundreds of PeerConnections, you can lower the buffer size to 256KiB (and divide the memory usage by nearly 4) like this, provided you apply the fix in https://github.com/murat-dogan/node-datachannel/pull/46 (the wrapper for `setSctpSettings` is currently broken):
```
nodeDataChannel.setSctpSettings({
    recvBufferSize: 262144,
    sendBufferSize: 262144,
});
```
If you want to reduce more, you also need to reduce the maximum message size:
```
nodeDataChannel.setSctpSettings({
    recvBufferSize: 65536,
    sendBufferSize: 65536,
});
[...]
let peer = new nodeDataChannel.PeerConnection("Peer", {
     iceServers: [...],
     maxMessageSize: 65536,
});
```

**Comment by murat-dogan** [comment]
It seems clear to me. So I am closing this. Thanks @paullouisageneau .

**Comment by bil-ash** [comment]
> Hi again,
> 
> I made some tests. Here is my findings;
> 
> * Memory consumption is related to peer connections count not data channels count.
> * With 200 open data channels within a single peer connection consumes only 20MB memory.
> * 200 peer connections consume 1200MB memory
> * I made a "dirty" test on libdatachannel (base lib);
>   
>   * For 200 peer connections it consumes ~2500MB
> 
> For me, it seems like it is related to base library.
> Probably it is expected, but you still can open a issue.
> https://github.com/paullouisageneau/libdatachannel

@murat-dogan  Please add an example showing how to create multiple datachannels per peer connection and also how **signalling** (description and candidate exchange )will work in such case. All the wrtc examples I have seen till now(both browser as well as node) demonstrate one datachannel per peer connection.

Context: I have a particular server-side use case where I will need to exchange messages using around 100 data channels,it dosen't matter if all of them are on same peer connection or 1 on each peer connection. According to your comment, there is huge memory saving if all the data channels are on the same peer connection, I tried doing so but could not carry out the signalling correctly. So, requesting a detailed example from with this specific use case.

**Comment by paullouisageneau** [comment]
> @bil-ash Please add an example showing how to create multiple datachannels per peer connection and also how signalling (description and candidate exchange )will work in such case. All the wrtc examples I have seen till now(both browser as well as node) demonstrate one datachannel per peer connection.

This was merely a test to find if the memory usage came for the number of Peer Connections or the number of Data Channels. The multiple Data Channels opened in a Peer Connection will be opened between the same two peers without more signaling messages. It's only useful to separate different streams (for instance files) or use different reliability parameters.

As I assume every Data Channel in your use case is opened with a different peer, it must be opened on a different Peer Connection. If you need to reduce memory usage, you should instead do as stated in https://github.com/murat-dogan/node-datachannel/issues/43#issuecomment-884399511

**Comment by paullouisageneau** [comment]
> Please add an example showing how to create multiple datachannels per peer connection and also how signalling (description and candidate exchange )will work in such case. All the wrtc examples I have seen till now(both browser as well as node) demonstrate one datachannel per peer connection.

@bil-ash This was merely a test to find if the memory usage came for the number of Peer Connections or the number of Data Channels. The multiple Data Channels opened in a Peer Connection will be opened between the same two peers without more signaling messages. It's only useful to separate different streams (for instance files) or use different reliability parameters.

As I assume every Data Channel in your use case is opened with a different peer, it must be opened on a different Peer Connection. If you need to reduce memory usage, you should instead do as stated in https://github.com/murat-dogan/node-datachannel/issues/43#issuecomment-884399511

**Comment by bil-ash** [comment]
Yes, my use case involves every data channel connecting to a different browser client. So, it seems (from your comment) that I will have to use one peer connection for every data channel. Thanks for clarifying.

**Comment by boa86** [comment]
Hi @paullouisageneau !
I returned to the task a few months later. 
I installed the latest version of node-datachanne@0.2.4, set recvBufferSize, sendBufferSize, maxMessageSize as you wrote. 
Suddenly I got the same result. It allocated 3GB memory.
If I change numbers nothing changes.

Could you please advice what I did wrong

`const nodeDataChannel = require('node-datachannel')

// Log Level
// nodeDataChannel.initLogger("Debug")

const MSG_SIZE = 65536

nodeDataChannel.setSctpSettings({
  recvBufferSize: MSG_SIZE,
  sendBufferSize: MSG_SIZE,
});


function createConnection(id) {
  let dc1 = null
  let dc2 = null
  let peer1 = null
  let peer2 = null

  const peerOnelabel = `Peer.${id}.1`
  const peerSecondlabel = `Peer.${id}.2`

  peer1 = new nodeDataChannel.PeerConnection(peerOnelabel, {
    iceServers: ["stun:stun.l.google.com:19302"],
    maxMessageSize: MSG_SIZE,
  })

  // Set Callbacks
  peer1.onStateChange((state) => {
    console.log(peerOnelabel, "State:", state)
  })
  peer1.onGatheringStateChange((state) => {
    // console.log(peerOnelabel, "GatheringState:", state)
  })
  peer1.onLocalDescription((sdp, type) => {
    // console.log(peerOnelabel, "SDP:", sdp, "Type:", type)
    peer2.setRemoteDescription(sdp, type)
  })
  peer1.onLocalCandidate((candidate, mid) => {
    // console.log(peerOnelabel, "Candidate:", candidate)
    peer2.addRemoteCandidate(candidate, mid)
  })

  peer2 = new nodeDataChannel.PeerConnection(peerSecondlabel, {
    iceServers: ["stun:stun.l.google.com:19302"],
    maxMessageSize: MSG_SIZE,
  })

  // Set Callbacks
  peer2.onStateChange((state) => {
    console.log(peerSecondlabel, "State:", state)
  })
  peer2.onGatheringStateChange((state) => {
    // console.log(peerSecondlabel, "GatheringState:", state)
  })
  peer2.onLocalDescription((sdp, type) => {
    // console.log(peerSecondlabel, "SDP:", sdp, "Type:", type)
    peer1.setRemoteDescription(sdp, type)
  })
  peer2.onLocalCandidate((candidate, mid) => {
    // console.log(peerSecondlabel, "Candidate:", candidate)
    peer1.addRemoteCandidate(candidate, mid)
  })
  peer2.onDataChannel((dc) => {
    // console.log(peerSecondlabel, "Got DataChannel:", dc.getLabel())
    dc2 = dc
    dc2.onMessage((msg) => {
      // console.log(peerSecondlabel, 'Received Msg:', msg)
    })
    dc2.sendMessage("Hello From" + peerSecondlabel)
  })

  dc1 = peer1.createDataChannel("test")
  dc1.onOpen(() => {
    dc1.sendMessage("Hello from" + peerOnelabel)
  })
  dc1.onMessage((msg) => {
    // console.log(peerOnelabel, 'Received Msg:', msg)
  })

  setTimeout(() => {
    console.log('Closed:', id)
    dc1 && dc1.close()
    dc2 && dc2.close()
    peer1 && peer1.close()
    peer2 && peer2.close()
    dc1 = null
    dc2 = null
    peer1 = null
    peer2 = null
    nodeDataChannel.cleanup()
  }, 5 * 1000)
}


function main() {
  for(let i = 0; i < 200; i++) {
    createConnection(i)
  }
}

main()`

**Comment by paullouisageneau** [comment]
After further checking, there is indeed another memory allocation done under the hood in usrsctp. In accordance with the RFC recommandation, libdatachannel sets the maximum number of supported SCTP streams to 65535, and it results in usrsctp allocating huge tables, which take most of the memory here.

Here is the issue: https://github.com/paullouisageneau/libdatachannel/issues/602

**Comment by boa86** [comment]
thank you for investigation! will be waiting for news from libdatachannel guys

**Comment by murat-dogan** [comment]
I can confirm that memory usage dropped from ~19MB to ~7MB for test/connectivity app (1 peer connection + 1 data connection)

**Comment by boa86** [comment]
I confirm the memory usage reduced from 3GB to ~89MB.
Thank you very much guys! Very appreciated! I'll continue making a datachannel server for my task. Probably will return with new question
