### ISSUE TITLE
 IceServer config error

### ISSUE THREAD

**Issue by ntdat99** [murat-dogan/node-datachannel#44]
I create peer connection like this 
`   _localPeer = new rtcDataChannel.PeerConnection("Peer", {
            iceServers: [{
                          urls: "stun:stun.services.mozilla.com",
                          username: "louis@mozilla.com",
                          credential: "webrtcdemo"
                      }, {
                          urls: ["stun:stun.example.com", "stun:stun-1.example.com"]
                      }]
        });`
and getting this error
`UnhandledPromiseRejectionWarning: TypeError: IceServer config error (hostname OR/AND port is not suitable`
Iam i do anything wrong?

**Comment by murat-dogan** [comment]
Hi,
Please check config interface;
```
export interface IceServer {
    hostname: string;
    port: Number;
    username?: string;
    password?: string;
    relayType?: RelayType;
}

export interface RtcConfig {
    iceServers: (string | IceServer)[];
    proxyServer?: ProxyServer;
    enableIceTcp?: boolean;
    portRangeBegin?: Number;
    portRangeEnd?: Number;
    maxMessageSize?: Number;
}
```

Normally stun server does not need a password but you can supply if you want.
Please use like ```[{hostname:"stun:stun.services.mozilla.com",port: XX,username:"XX",password:"XX"}]```

**Comment by ntdat99** [comment]
Most of ice server configuration i see has this construct 

`{
  'iceServers': [
    {
      'urls': 'stun:stun.l.google.com:19302'
    },
    {
      'urls': 'turn:192.158.29.39:3478?transport=udp',
      'credential': 'JZEOEt2V3Qb0y27GRntt2u2PAYA=',
      'username': '28224511:1379330808'
    },
    {
      'urls': 'turn:192.158.29.39:3478?transport=tcp',
      'credential': 'JZEOEt2V3Qb0y27GRntt2u2PAYA=',
      'username': '28224511:1379330808'
    }
  ]
}`
STUN didnt use credential and username but TURN did
So if i use TURN instead of STUN where I can place my username and credential
tks for help.

**Comment by murat-dogan** [comment]
You can use URI like 
```
iceServers = [
"stun:SERVER:PORT",
"turn:USER:PASSWORD@SERVER:PORT"
]
```

Please see https://tools.ietf.org/html/rfc3986#appendix-B

**Comment by murat-dogan** [comment]
I am closing this. If you have any other question please re-open it.
