### ISSUE TITLE
Prebuilt binary missing for Alpine Linux @ node v14

### ISSUE THREAD

**Issue by ThatOneBro** [murat-dogan/node-datachannel#45]
Upon installing on an Alpine Linux Docker image (node:14-alpine) I got the following warning and then a failure:
```prebuild-install WARN install No prebuilt binaries found (target=14.17.1 runtime=node arch=x64 libc=musl platform=linux)```

I was able to get it working after building it myself but this complicates the build process a little. Any way we can get a prebuilt binary added for alpine?

**Comment by murat-dogan** [comment]
Hi,

It seems alpine is using musl  and default is glibc for node.
I tried with ```node:14-buster``` and it was ok.

For now we don't have prebuilt binaries  compiled against musl.

**Comment by murat-dogan** [comment]
Any update on this or may I close this issue?

**Comment by ThatOneBro** [comment]
Hello,

Sorry for the late update. I forgot to mention that I switched to ```node:1-buster``` as mentioned, and that worked okay. Thanks for checking, I'll go ahead and close the issue.

**Comment by ErikSom** [comment]
Wow i've spend so long trying to fix this, simple switch to node:14-buster solved it!, i had the error: 
`Makefile:160: recipe for target 'all' failed make` for any future person googling this.
