### ISSUE TITLE
Unable to send binary data using a <Buffer> object

### ISSUE THREAD

**Issue by Gronis** [murat-dogan/node-datachannel#49]
Sending binary data using a buffer object seems to not work. Receiving buffer data in onmessage seems to work though.

Sender Code (node-datachannel implementation):
```js
if (!(typeof data === 'string' || data instanceof String)) {
    console.log("sending non string data", data);
}
channel1.sendMessage(data);
```
Receiver Code (node-datachannel implementation):
```js
channel2.onMessage(data => {
    console.log("got msg", data);
})
```

Sending buffer data from node-datachannel implementation:
```log
sending non string data <Buffer 22 02 08 00>
(node:52366) UnhandledPromiseRejectionWarning: TypeError: String or Null expected
```

Sending data from wrtc implementation and receive in node-datachannel implementation:
```log
got msg <Buffer 1a 0c 0a 05 72 6f 62 69 6e 12 03 61 73 64>
```

**Comment by Gronis** [comment]
Ok, after spending 2min looking at the source code I realized there is a function for sending binary data.
```js
if (typeof data === 'string' || data instanceof String) {
    channel1.sendMessage(data);
} else if (data instanceof Buffer) {
    channel1.sendMessageBinary(data);
}
```

**Comment by murat-dogan** [comment]
I am glad that you found the right function. 
Maybe I could merge functions to make it easier to use.

**Comment by Gronis** [comment]
I think it works as it is right now. People can easily write a wrapper around it if they want one single function. Now there is some documentation about it here for people to find out about it 🙂
