### ISSUE TITLE
Symbol not found on OS X < 10.15, possible to build it for OS X 10.13?

### ISSUE THREAD

**Issue by watch-janick** [murat-dogan/node-datachannel#50]
Hello,

I'm running into a problem with the library, as `node_datachannel.node` has been built for OS X 10.15 and I'm currently on OS X 10.13, I get this error on runtime:
```
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/[...]/node_modules/@geckos.io/server/node_modules/node-datachannel/build/Release/node_datachannel.node (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
```

Do you think I could rebuild `node-datachannel.node` on my OS to make it compatible or it doesn't make sense?

I've tried by cloning the repository and install it locally, which I thought would rebuild `node_datachannel.node` for my OS version, but when trying to use it (basically replacing manually `node_datachannel.node` from the `node_modules` directory of `@geckos.io` in my project for testing purpose), I get the same error message.

So two things, either I haven't correctly rebuilt it / replaced it, or rebuilding it on my system doesn't change the part of the code which needs OS X 10.15 to work.

Any insights?

Thanks! :)

**Comment by murat-dogan** [comment]
Hi
Sorry for late reply.
I don’t have any experience with Mac and I don’t have one.
So I can’t test it. 
Prebuilt binaries are coming from GitHub actions.

Anyway if you build it locally, it should work.
Just clone the repo and then run 
npm run build

**Comment by murat-dogan** [comment]
Hi
Is this problem still exists?
Did you solve your problem?
Thanks,

**Comment by watch-janick** [comment]
> Hi Is this problem still exists? Did you solve your problem? Thanks,

Hello,

I believe it still exists.
I have tried to compile it myself at the time but I couldn't succeed as I had some problems with Xcode then GCC etc...

In the end, I used a websocket connection instead.

**Comment by murat-dogan** [comment]
I am sorry but I don't have access to a MAC, so I could not help it.

**Comment by murat-dogan** [comment]
The issue seems outdated. I am closing it as it is.
If you have further issues/questions please open a new one.
Thanks.
