### ISSUE TITLE
At some point, it starts to use full cpu.

### ISSUE THREAD

**Issue by amunhoz** [murat-dogan/node-datachannel#52]
Really dont know why, there is no console output.
I'm using a restricted port range with portRangeBegin and portRangeEnd.
It works at first test, then, at some point, it starts to use full cpu and inoperate the hole microservice.

**Comment by murat-dogan** [comment]
As I understand you solved your problem.
If it is related to this repo, Could you  please share it for reference?
Thanks anyway

**Comment by amunhoz** [comment]
Could not find the problem yet, and i dont know if is about this module.
