### ISSUE TITLE
Prebuild missing for linux-x64

### ISSUE THREAD

**Issue by hybridherbst** [murat-dogan/node-datachannel#68]
I was trying to test geckos.io on glitch.com, but found that when installing, I get the following message that points to node-datachannel:
```
npm ERR! prebuild info begin Prebuild version 11.0.0
npm ERR! prebuild info build Preparing to prebuild node-datachannel@0.1.13 for node 16.12.0 on linux-x64 using cmake-js
npm ERR! info TOOL Using Unix Makefiles generator.
npm ERR! ERR! OMG CMake executable is not found. Please use your system's package manager to install it, or you can get installers from there: http://cmake.org.
npm ERR! prebuild ERR! build Error: Failed to build cmake with exit code 1
```

I'm not really familiar with how prebuilding works, but given some other issues that were open here I think this points to 
a) glitch not having cmake (which is expected)
b) a specific prebuild missing so it's even trying to build from source

Is this correct? Or is it wrong for me to assume that Cmake shouldn't be necessary if the correct prebuild version would be found during installation?

Thanks!

**Comment by murat-dogan** [comment]
Hi,
node V16.x has a prebuilt binary, so you should not need cmake or other build tools.
As I see you are using node-datachannel v0.1.13. 
Here is the binary link : https://github.com/murat-dogan/node-datachannel/releases/download/v0.1.13/node-datachannel-v0.1.13-node-v93-linux-x64.tar.gz

Normally install script should find & download it automatically.
 Could you please try it manually first?
Just extract this file inside to node-datachannel folder.
After extracting you should have a file like this;
`node-datachannel/build/Release\node_datachannel.node`

You can test the file by executing `connectivity.js`.
`node test\connectivity.js`

**Comment by hybridherbst** [comment]
Hi, thanks for the reply. The issue seems to be that something about the order of operations doesn't work on Glitch, as the downloaded file seems to get deleted, not entirely sure. So most likely this is an issue with them, not node-datachannel. Thanks for your help!

(the same happens on Glitch and Replit)
