### ISSUE TITLE
"media" example is not entirely clear.

### ISSUE THREAD

**Issue by edbek** [murat-dogan/node-datachannel#70]
Running the "media" example is not entirely clear. Could you explain in more detail how this example was launched?
Thanks.

**Comment by murat-dogan** [comment]
Hi,

It is pretty new  actually.

Could you please check readme in https://github.com/murat-dogan/node-datachannel/tree/master/examples/media?

I updated it.

If it is still not clear, please let me know.

**Comment by edbek** [comment]
This example does not work for Windows. Not sure what the problem is?
Thanks.

**Comment by murat-dogan** [comment]
I tried on windows today.
Connection seems ok. 
I don't have gstreamer on windows, so I could not check the video but it seems ok.

What is the error that you get?

**Comment by murat-dogan** [comment]
I am closing this.
If you have further questions please feel free to re-open it.
Thanks.
