### ISSUE TITLE
onStateChange 'closed' callback never fires when close() is called

### ISSUE THREAD

**Issue by pimterry** [murat-dogan/node-datachannel#87]
[Apparently](https://github.com/paullouisageneau/libdatachannel/issues/574#issuecomment-1065461413) in libdatachannel, the state change callback is always called synchronously when `close()` is called. This is useful for consistent handling of connection shutdown.

In node-datachannel, this doesn't happen. When `close()` is called, the `onStateChange` callback doesn't fire at all.

This appears to be intentional, since the onStateChange callback is explicitly reset before the connection is actually closed: https://github.com/murat-dogan/node-datachannel/blob/8d60cc20a8fb5b0fcf993266d35ca283bc2c1d71/src/peer-connection-wrapper.cpp#L230-L237

It looks like `DataChannelWrapper::doClose` does the same thing too, which doesn't matter now (since that event currently doesn't fire after local close) but will matter in the next release that updates libdatachannel, since it means we can't use the upcoming new behaviour from https://github.com/paullouisageneau/libdatachannel/pull/576 from JS.

Is there a reason for this? If not, it'd be great if the callbacks weren't reset for either connections or channels until after `close()` has completed.

**Comment by paullouisageneau** [comment]
In order to accommodate the new behavior from https://github.com/paullouisageneau/libdatachannel/pull/576, not only the callbacks must be reset later, but also the scheduled callback must not be cancelled when it runs after close: https://github.com/murat-dogan/node-datachannel/blob/8d60cc20a8fb5b0fcf993266d35ca283bc2c1d71/src/data-channel-wrapper.cpp#L310

I'll try to open a PR when I get a moment.

**Comment by murat-dogan** [comment]
Hi,
I think moving reset logic to onClosed cb will fix it.
Could you please test from your side?

Pleae check https://github.com/murat-dogan/node-datachannel/pull/89

**Comment by pimterry** [comment]
Hi @murat-dogan, with that PR it appears to correctly support the changes from https://github.com/paullouisageneau/libdatachannel/pull/576 (i.e. the channel's onClosed callback is now called when the peer is locally closed) which is great!

It doesn't solve the main issue above though: that when a peer connection is closed, the `onStateChange` callback is never called.

It looks like that PR only fixes this issue for media tracks & datachannels - is it possible to make the same change in peer-connection?

**Comment by murat-dogan** [comment]
Hi @pimterry ,

New commits should fix it too. Could you please try it?

And two notes;
- If user closes pc or dc, then instances could not be used again. For making new pc or dc, user must create new instances.
- Peer connection close event is called only if user call `close` function. On other side `disconnected` event will be fired

Anything to say about notes @paullouisageneau @pimterry

**Comment by paullouisageneau** [comment]
> And two notes;
> 
>     * If user closes pc or dc, then instances would not be used again. For making new pc or dc, user must create new instances.
> 
>     * Peer connection close event is fired only if user call `close` function. On other side `disconnected` event will be fired

It looks right to me! To ensure the `PeerConnection` is closed on disconnect, you would need to call `close` when the state changes to `Disconnected`. The reason is that the state machine mimics the one of the browser API.

**Comment by murat-dogan** [comment]
For me it is all ok.
I merged it.

@pimterry please check it when you have time, and everything is ok then we can closed the issue!

I will release v0.3.0 today. This seems a breaking change so I will pump the vesion from 0.2.x to 0.3.0.

Thanks!

**Comment by paullouisageneau** [comment]
> I will release v0.3.0 today. This seems a breaking change so I will pump the vesion from 0.2.x to 0.3.0.

I'll release the next libdatachannel version in a couple days, if you want you can wait for it to release on your side.

**Comment by paullouisageneau** [comment]
> I will release v0.3.0 today. This seems a breaking change so I will pump the vesion from 0.2.x to 0.3.0.

@murat-dogan I'll release the next libdatachannel version in a couple days, if you want you can wait for it to release on your side.

**Comment by murat-dogan** [comment]
Sure. Thanks for the info.

**Comment by pimterry** [comment]
Tested - looks good to me now! I see the 'closed' state update callbacks on peers and closed callback on the datachannels. Thanks guys :+1: :+1: :+1:

**Comment by murat-dogan** [comment]
You are right.
I forgot to move state cb call to constructor on peer connection that @paullouisageneau mentioned.
Let me fix it

**Comment by murat-dogan** [comment]
Now it is fixed. Could you please try it again?

**Comment by pimterry** [comment]
Thanks for the quick fix @murat-dogan! With those changes, removing the manual shutdown from the test now works correctly with no dangling handles: https://github.com/murat-dogan/node-datachannel/pull/91. All looks good to me :+1:
