### ISSUE TITLE
How to install with npm ?

### ISSUE THREAD

**Issue by DarePhoenix** [murat-dogan/node-datachannel#92]
Hello, I'm trying to install node-datachannel with npm on windows 10 with

`npm i node-datachannel`

(using latest node and npm versions)

I got an error the first time, and someone said me to install cmake, visual studio compilers, git and openssl

I have installed them, but I'm getting other errors :

![image](https://user-images.githubusercontent.com/86203108/161107447-7d8a6f67-ff4e-4e35-9d02-9341643534b5.png)

![image](https://user-images.githubusercontent.com/86203108/161107515-abb09ca0-a9ba-4691-806d-2dba1ec94992.png)

![image](https://user-images.githubusercontent.com/86203108/161107601-f07b473b-e032-4557-a734-8d06da8c9113.png)

![image](https://user-images.githubusercontent.com/86203108/161107679-0ab5f251-c353-40bb-be00-522332679b58.png)

I dont get what is happening, and how can I fix it.

Can someone please explain me how can I install node-datachannel via npm ?

Note that I never used git, cmake, openssl or any c++/c compiler, so I may just doing stupid errors.

Thanks for help

**Comment by murat-dogan** [comment]
Hi,

Normally you don't need any tools like cmake etc.
`node-datachannel` has prebuilt binaries for certain node versions.
        node-version: [10.x, 11.x, 12.x, 13.x, 14.x, 15.x, 16.x]

As I see you are using V17. 
I can add V17 to the next release, until that you can use one of the supported versions listed above.

**Comment by paullouisageneau** [comment]
@DarePhoenix Also the error you encountered is actually not a build error, it's a network error while cloning the repository (the connection was reset):
```
error : RPC failed; curl 56 OpenSSL SSL_read: Connection was reset
```
